import type { EndpointRiskLevel } from 'corsair/core';

export type AnchorBrowserMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type AnchorBrowserRoute = {
	key: string;
	group: string;
	name: string;
	method: AnchorBrowserMethod;
	path: string;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const anchorBrowserRoutes = [
	{
		key: 'clickMouse',
		group: 'osLevel',
		name: 'clickMouse',
		method: 'POST',
		path: '/sessions/{sessionId}/mouse/click',
		description:
			'Tool to perform a mouse click at specified coordinates within a browser session. Use when you need to interact with page elements by clicking at specific x/y positions. The click is executed in the context of the specified browser session.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'copySelectedText',
		group: 'osLevel',
		name: 'copySelectedText',
		method: 'POST',
		path: '/sessions/{sessionId}/copy',
		description:
			'Tool to copy currently selected text in a browser session to the clipboard. Use when you need to extract text that the user or automation has selected in the browser.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createIntegration',
		group: 'integrations',
		name: 'createIntegration',
		method: 'POST',
		path: '/integrations',
		description:
			'Tool to create a new integration with a third-party service like 1Password. Use when you need to set up an integration for managing credentials or accessing external services. The integration will be available immediately after creation for use in browser sessions and profiles.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createOrUpdateTaskDraft',
		group: 'tasks',
		name: 'createOrUpdateTaskDraft',
		method: 'POST',
		path: '/task/{taskId}/draft',
		description:
			'Tool to create or update the draft version of a task. Draft versions are used for development and testing before publishing. Use when you need to save task code changes without creating a published version.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createProfile',
		group: 'profiles',
		name: 'createProfile',
		// Anchor API persists session state to a new profile via POST /profiles.
		method: 'POST',
		path: '/profiles',
		description:
			'Creates a new browser profile from an active session. A profile stores cookies, local storage, and cache data. The session must be running when this is called; profile data is persisted once the session terminates. Use profiles to maintain persistent browser state across multiple sessions.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createTask',
		group: 'tasks',
		name: 'createTask',
		method: 'POST',
		path: '/task',
		description:
			'Tool to create a new task or update an existing task with the same name. Tasks are reusable TypeScript code snippets that execute in browser sessions. Use when you need to define repeatable automation workflows that can be invoked across multiple sessions.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'deleteExtension',
		group: 'extensions',
		name: 'deleteExtension',
		method: 'DELETE',
		path: '/extensions/{id}',
		description:
			'Tool to delete a browser extension and remove it from storage. Use after confirming the extension exists.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteIntegration',
		group: 'integrations',
		name: 'deleteIntegration',
		method: 'DELETE',
		path: '/integrations/{integrationId}',
		description:
			'Tool to delete an existing integration and remove its stored credentials. Use after confirming the integration ID exists.',
		pathParams: ['integrationId'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteProfile',
		group: 'profiles',
		name: 'deleteProfile',
		method: 'DELETE',
		path: '/profiles/{name}',
		description:
			'Tool to delete a browser profile by ID. Use after confirming the profile exists.',
		pathParams: ['name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteTask',
		group: 'tasks',
		name: 'deleteTask',
		method: 'DELETE',
		path: '/task/{taskId}',
		description:
			'Tool to soft delete a task and all its versions. Use after confirming the task exists.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteTaskVersion',
		group: 'tasks',
		name: 'deleteTaskVersion',
		method: 'DELETE',
		path: '/task/{taskId}/{taskVersion}',
		description:
			'Tool to soft delete a specific version of a task. The version will no longer be accessible but data is preserved for recovery. Use when you need to remove a specific task version.',
		pathParams: ['taskId', 'taskVersion'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deployTask',
		group: 'tasks',
		name: 'deployTask',
		method: 'POST',
		path: '/task/{taskId}/deploy',
		description:
			'Tool to deploy a task by creating a new version with auto-incremented version number. Use when you need to publish task changes and make them available for execution.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'doubleClickMouse',
		group: 'osLevel',
		name: 'doubleClickMouse',
		method: 'POST',
		path: '/sessions/{sessionId}/mouse/doubleClick',
		description:
			'Tool to perform a double click at specified coordinates in a browser session. Use when you need to trigger double-click events on UI elements or specific page locations.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'dragAndDrop',
		group: 'osLevel',
		name: 'dragAndDrop',
		method: 'POST',
		path: '/sessions/{sessionId}/drag-and-drop',
		description:
			'Tool to perform a drag and drop operation from start coordinates to end coordinates within a browser session. Use when you need to simulate dragging UI elements or files in automated workflows.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'endAllSessions',
		group: 'sessions',
		name: 'endAllSessions',
		method: 'DELETE',
		path: '/sessions/all',
		description:
			'Tool to terminate all active browser sessions at once. Use when you need to immediately close every browser session for the authenticated user, such as during cleanup operations or security concerns.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'endBrowserSession',
		group: 'sessions',
		name: 'endBrowserSession',
		method: 'DELETE',
		path: '/sessions/{sessionId}',
		description:
			'Tool to end a specific browser session by ID. Use after confirming the session ID you want to terminate.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'getBatchSessionStatus',
		group: 'batchSessions',
		name: 'getBatchSessionStatus',
		method: 'GET',
		path: '/batch-sessions/{batchId}',
		description:
			'Tool to retrieve detailed status information for a specific batch including progress and errors. Use when you need to check the status of a batch session creation request.',
		pathParams: ['batchId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getBrowserSession',
		group: 'sessions',
		name: 'getBrowserSession',
		method: 'GET',
		path: '/sessions/{sessionId}',
		description:
			'Tool to retrieve detailed information about a specific browser session. Use when you need to check the status, configuration, or execution details of a browser session.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getClipboardContent',
		group: 'osLevel',
		name: 'getClipboardContent',
		method: 'GET',
		path: '/sessions/{sessionId}/clipboard',
		description:
			'Tool to retrieve the current content of the clipboard from a browser session. Use when you need to read clipboard data from an active session.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getLatestTaskVersion',
		group: 'tasks',
		name: 'getLatestTaskVersion',
		method: 'GET',
		path: '/task/{taskId}/latest',
		description:
			'Tool to retrieve the latest version of a task including the full base64 encoded code content. Use when you need to access the most recent task implementation.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getProfile',
		group: 'profiles',
		name: 'getProfile',
		method: 'GET',
		path: '/profiles/{name}',
		description:
			'Tool to retrieve details of a specific profile by its name. Use when you need to fetch information about a particular browser profile.',
		pathParams: ['name'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSessionPages',
		group: 'pages',
		name: 'getSessionPages',
		method: 'GET',
		path: '/sessions/{sessionId}/pages',
		description:
			'Tool to retrieve all pages associated with a specific browser session. Use when you need to list all open tabs or pages in an active or completed session.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTaskDraft',
		group: 'tasks',
		name: 'getTaskDraft',
		method: 'GET',
		path: '/task/{taskId}/draft',
		description:
			"Tool to retrieve the draft version of a task, including the full Base64 encoded code content. Use when you need to access the current draft of a task that hasn't been published yet.",
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTaskExecutionResult',
		group: 'tasks',
		name: 'getTaskExecutionResult',
		method: 'GET',
		path: '/task/{taskId}/executions/{executionId}',
		description:
			'Tool to retrieve a single task execution result by its ID. Use when you need to check the status, output, or error details of a specific task execution.',
		pathParams: ['taskId', 'executionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTaskMetadata',
		group: 'tasks',
		name: 'getTaskMetadata',
		method: 'GET',
		path: '/task/{taskId}',
		description:
			'Tool to retrieve task metadata without downloading the full task code. Use when you need task information such as status, creation time, or language without the code content.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTaskVersion',
		group: 'tasks',
		name: 'getTaskVersion',
		method: 'GET',
		path: '/task/{taskId}/{taskVersion}',
		description:
			'Tool to retrieve a specific version of a task, including the full code content. Use when you need to access the complete task code for a particular version (draft, latest, or specific version number).',
		pathParams: ['taskId', 'taskVersion'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getWebpageContent',
		group: 'tools',
		name: 'getWebpageContent',
		method: 'POST',
		path: '/tools/fetch/webpage',
		description:
			'Tool to retrieve rendered content of a webpage in HTML or Markdown format. Use when you need to fetch a page’s full content, optionally within an existing browser session.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'listAgentResources',
		group: 'agent',
		name: 'listAgentResources',
		method: 'GET',
		path: '/sessions/{sessionId}/agent/files',
		description:
			'List all agent resources (files) uploaded to a browser session. Returns metadata for each file including name, size, file type, and last modified timestamp. Requires an active running session - use START_BROWSER_SESSION first. Files can be uploaded using UPLOAD_FILE action.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listExtensions',
		group: 'extensions',
		name: 'listExtensions',
		method: 'GET',
		path: '/extensions',
		description:
			'Retrieves all browser extensions uploaded by the authenticated user. Use this to view available extensions that can be attached to browser sessions for automation tasks.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listIntegrations',
		group: 'integrations',
		name: 'listIntegrations',
		method: 'GET',
		path: '/integrations',
		description:
			'Tool to retrieve all integrations for the authenticated team. Use when you need to view available integrations that can be used with browser sessions.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listProfiles',
		group: 'profiles',
		name: 'listProfiles',
		method: 'GET',
		path: '/profiles',
		description:
			'Tool to fetch all stored browser profiles. Use when you need an overview of all profiles available to the authenticated user (e.g., after creating or deleting profiles).',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listSessionDownloads',
		group: 'downloads',
		name: 'listSessionDownloads',
		method: 'GET',
		path: '/sessions/{sessionId}/downloads',
		description:
			'Tool to retrieve metadata of files downloaded during a browser session. Use after confirming the session ID.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listSessionRecordings',
		group: 'recordings',
		name: 'listSessionRecordings',
		method: 'GET',
		path: '/sessions/{sessionId}/recordings',
		description:
			'Tool to list all recordings for a specific browser session. Use after confirming the session ID.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listSessions',
		group: 'sessions',
		name: 'listSessions',
		method: 'GET',
		path: '/sessions',
		description:
			'Tool to list all browser sessions. Use when you need to retrieve both active and inactive sessions.',
		pathParams: [],
		queryParams: [
			'page',
			'limit',
			'sort_by',
			'sort_order',
			'search',
			'status',
			'tags',
			'domains',
			'created_from',
			'created_to',
			'batch_id',
			'task_initiated',
			'playground',
			'proxy',
			'extra_stealth',
			'profile_name',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listTaskExecutions',
		group: 'tasks',
		name: 'listTaskExecutions',
		method: 'GET',
		path: '/task/{taskId}/executions',
		description:
			'Tool to retrieve execution history for a specific task with filtering and pagination support. Use when you need to view past execution results, monitor task success rates, or debug failed executions.',
		pathParams: ['taskId'],
		queryParams: ['page', 'limit', 'status', 'version'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listTasks',
		group: 'tasks',
		name: 'listTasks',
		method: 'GET',
		path: '/task',
		description:
			'Tool to retrieve a paginated list of all tasks for the authenticated team. Use when you need to view available tasks with their latest version information and metadata.',
		pathParams: [],
		queryParams: ['page', 'limit'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listTaskVersions',
		group: 'tasks',
		name: 'listTaskVersions',
		method: 'GET',
		path: '/task/{taskId}/versions',
		description:
			'Tool to retrieve all versions of a specific task, including draft and published versions. Use when you need to view the version history of a task or select a specific version for deployment or execution.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'moveMouse',
		group: 'osLevel',
		name: 'moveMouse',
		method: 'POST',
		path: '/sessions/{sessionId}/mouse/move',
		description:
			'Tool to move the mouse cursor to specified coordinates within a browser session. Use when you need to simulate mouse movement at the OS level.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'navigateToUrl',
		group: 'osLevel',
		name: 'navigateToUrl',
		method: 'POST',
		path: '/sessions/{sessionId}/goto',
		description:
			'Tool to navigate a browser session to a specified URL. Use when you need to direct an existing session to a new webpage.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'pasteText',
		group: 'osLevel',
		name: 'pasteText',
		method: 'POST',
		path: '/sessions/{sessionId}/paste',
		description:
			'Tool to paste text at the current cursor position in a browser session. Use when you need to insert text into an active form field or text area.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'pauseAgent',
		group: 'agent',
		name: 'pauseAgent',
		method: 'POST',
		path: '/sessions/{sessionId}/agent/pause',
		description:
			'Tool to pause the AI agent for a specific browser session. Use when you need to temporarily halt autonomous agent execution while keeping the session active.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'pauseSessionRecording',
		group: 'recordings',
		name: 'pauseSessionRecording',
		method: 'POST',
		path: '/sessions/{sessionId}/recordings/pause',
		description:
			'Tool to pause the video recording for a specific browser session. Use when you need to temporarily stop recording without ending the session.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'performKeyboardShortcut',
		group: 'osLevel',
		name: 'performKeyboardShortcut',
		method: 'POST',
		path: '/sessions/{sessionId}/keyboard/shortcut',
		description:
			'Tool to perform a keyboard shortcut using specified keys in a browser session. Use when you need to simulate keyboard input like copy (Control+C), paste (Control+V), or any other key combination.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'performWebTask',
		group: 'tools',
		name: 'performWebTask',
		method: 'POST',
		path: '/tools/perform-web-task',
		description:
			'Tool to perform autonomous web tasks using AI agents. Use when you need to automate complex browser interactions like form filling, data extraction, or multi-step workflows.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'pressMouseButton',
		group: 'osLevel',
		name: 'pressMouseButton',
		method: 'POST',
		path: '/sessions/{sessionId}/mouse/down',
		description:
			'Tool to perform a mouse button down action at specified coordinates within a browser session. Use when you need to simulate pressing and holding a mouse button at a specific screen position.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'publishTaskVersion',
		group: 'tasks',
		name: 'publishTaskVersion',
		method: 'POST',
		path: '/task/{taskId}/{taskVersion}',
		description:
			"Tool to publish a specific version of a task. Creates a new version if it doesn't exist, or updates an existing version's metadata. Use when you need to make a specific task version available for execution. Cannot publish to 'draft' versions.",
		pathParams: ['taskId', 'taskVersion'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'releaseMouseButton',
		group: 'osLevel',
		name: 'releaseMouseButton',
		method: 'POST',
		path: '/sessions/{sessionId}/mouse/up',
		description:
			'Tool to release a mouse button at specified coordinates within a browser session. Use when automating mouse interactions that require button release events, such as completing drag operations or simulating natural mouse behavior.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'resumeAgent',
		group: 'agent',
		name: 'resumeAgent',
		method: 'POST',
		path: '/sessions/{sessionId}/agent/resume',
		description:
			'Tool to resume the AI agent for a specific browser session. Use when you need to restart agent execution after it has been paused or stopped.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'resumeSessionRecording',
		group: 'recordings',
		name: 'resumeSessionRecording',
		method: 'POST',
		path: '/sessions/{sessionId}/recordings/resume',
		description:
			'Tool to resume video recording for a specific browser session. Use when recording was previously paused and needs to be restarted.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'runTask',
		group: 'tasks',
		name: 'runTask',
		method: 'POST',
		path: '/task/run',
		description:
			'Tool to execute a task in a browser session with a specific or latest version. Use when you need to run an existing task with optional session reuse and configuration overrides.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'runTaskByName',
		group: 'tasks',
		name: 'runTaskByName',
		method: 'POST',
		path: '/task/run/{taskName}',
		description:
			'Tool to execute a task by its name, always using the latest version. Use when you need to run a predefined browser automation task by referencing its name.',
		pathParams: ['taskName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'screenshotWebpage',
		group: 'tools',
		name: 'screenshotWebpage',
		method: 'POST',
		path: '/tools/screenshot',
		description:
			'Tool to take a screenshot of a specified webpage within a session. Use when you need a visual PNG snapshot of a live page. Example: "Capture a 1280×720 screenshot of https://example.com".',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'scrollSession',
		group: 'osLevel',
		name: 'scrollSession',
		method: 'POST',
		path: '/sessions/{sessionId}/scroll',
		description:
			'Tool to perform a scroll action at specified coordinates within a browser session. Use when you need to scroll to specific positions or simulate user scrolling behavior. Example: "Scroll down 100 pixels from position (100, 100) in session sess_123".',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'setClipboardContent',
		group: 'osLevel',
		name: 'setClipboardContent',
		method: 'POST',
		path: '/sessions/{sessionId}/clipboard',
		description:
			'Tool to set the content of the clipboard in a browser session. Use when you need to programmatically copy text to the clipboard for automated workflows.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'signalEvent',
		group: 'events',
		name: 'signalEvent',
		method: 'POST',
		path: '/events/{eventName}',
		description:
			'Tool to signal a specific event to be received by other processes or sessions. Use when you need real-time coordination across browser sessions after verifying session is active.',
		pathParams: ['eventName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'startBrowserSession',
		group: 'sessions',
		name: 'startBrowserSession',
		method: 'POST',
		path: '/sessions',
		description:
			'Tool to start a new browser session with optional customizations. Use when you need to programmatically allocate an isolated browser instance with recording, proxy, live view, and feature toggles.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'takeScreenshot',
		group: 'screenshots',
		name: 'takeScreenshot',
		method: 'GET',
		path: '/sessions/{sessionId}/screenshot',
		description:
			'Tool to take a screenshot of the current browser session and return it as an image. Use when you need a visual snapshot of an active browser session.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'typeText',
		group: 'osLevel',
		name: 'typeText',
		method: 'POST',
		path: '/sessions/{sessionId}/keyboard/type',
		description:
			'Tool to type specified text with optional delay between keystrokes. Use when you need to input text into a browser session, such as filling forms or entering search queries.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateProfile',
		group: 'profiles',
		name: 'updateProfile',
		// Anchor API refreshes an existing profile from a session via the same POST /profiles route.
		method: 'POST',
		path: '/profiles',
		description:
			'Updates an existing browser profile with data from an active session. The profile stores cookies, local storage, and cache from the session. Requires an active (running) browser session - the session_id must reference a session that has not been terminated.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTaskMetadata',
		group: 'tasks',
		name: 'updateTaskMetadata',
		method: 'PUT',
		path: '/task/{taskId}',
		description:
			'Updates task metadata (name and description). This does not affect the task code or versions. Use when you need to update task information without modifying the implementation.',
		pathParams: ['taskId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'uploadExtension',
		group: 'extensions',
		name: 'uploadExtension',
		method: 'POST',
		path: '/extensions',
		description:
			'Tool to upload a new browser extension as a ZIP file for use in browser sessions. Use when you need to add custom extensions that can be attached to automation sessions. The ZIP file must contain a valid extension manifest (manifest.json). Extensions are scoped to the authenticated user and can be listed or attached to sessions later.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'uploadFile',
		group: 'agent',
		name: 'uploadFile',
		method: 'POST',
		path: '/sessions/{sessionId}/agent/files',
		description:
			'Tool to upload a file to a browser session as an agent resource. Use after starting or referencing a session when you need to provide file inputs (single files or ZIP archives) for web forms or AI-driven tasks. Supports direct base64-encoded content or S3 key references from other actions.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'uploadFilesToSession',
		group: 'uploads',
		name: 'uploadFilesToSession',
		method: 'POST',
		path: '/sessions/{sessionId}/uploads',
		description:
			'Tool to upload files directly to a browser session for use with web forms and file inputs. Use when you need to provide file inputs to web forms during automated browser sessions.',
		pathParams: ['sessionId'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'waitForEvent',
		group: 'events',
		name: 'waitForEvent',
		method: 'POST',
		path: '/events/{eventName}/wait',
		description:
			'Blocks execution until a specific named event is signaled or the timeout expires. Used for cross-session coordination, MFA handling, and workflow synchronization. The event must first be signaled using the Signal Event action. Returns the data payload that was sent with the signal. Events are user-scoped.',
		pathParams: ['eventName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
] as const;

export type AnchorBrowserRoutes = typeof anchorBrowserRoutes;
