import {
	BrexBudget,
	BrexCard,
	BrexCashAccount,
	BrexCompany,
	BrexDepartment,
	BrexExpense,
	BrexField,
	BrexLegalEntity,
	BrexLocation,
	BrexReferral,
	BrexSpendLimit,
	BrexTitle,
	BrexTransaction,
	BrexTransfer,
	BrexTrip,
	BrexUser,
	BrexVendor,
	BrexWebhookSubscription,
} from './database';

export const BrexSchema = {
	version: '1.0.0',
	entities: {
		users: BrexUser,
		cards: BrexCard,
		departments: BrexDepartment,
		locations: BrexLocation,
		titles: BrexTitle,
		company: BrexCompany,
		legalEntities: BrexLegalEntity,
		expenses: BrexExpense,
		transactions: BrexTransaction,
		budgets: BrexBudget,
		spendLimits: BrexSpendLimit,
		vendors: BrexVendor,
		transfers: BrexTransfer,
		referrals: BrexReferral,
		webhooks: BrexWebhookSubscription,
		fields: BrexField,
		trips: BrexTrip,
		cashAccounts: BrexCashAccount,
	},
} as const;

export {
	BrexBudget,
	BrexCard,
	BrexCashAccount,
	BrexCompany,
	BrexDepartment,
	BrexExpense,
	BrexField,
	BrexLegalEntity,
	BrexLocation,
	BrexReferral,
	BrexSpendLimit,
	BrexTitle,
	BrexTransaction,
	BrexTransfer,
	BrexTrip,
	BrexUser,
	BrexVendor,
	BrexWebhookSubscription,
} from './database';
