import type { EndpointRiskLevel } from 'corsair/core';

export type WorkdayMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
export type WorkdayService =
	| 'staffing'
	| 'absenceManagement'
	| 'recruiting'
	| 'payroll'
	| 'common'
	| 'person';

export type WorkdayRoute = {
	key: string;
	group: string;
	name: string;
	method: WorkdayMethod;
	service: WorkdayService;
	version: string;
	path: string;
	description: string;
	pathParams: readonly string[];
	queryParams: readonly string[];
	riskLevel: EndpointRiskLevel;
};

/**
 * Workday REST routes (85 ops).
 * Paths verified against Workday REST Directory + Staffing v6 prompt/resource docs.
 * Base: https://{host}/ccx/api/{service}/{version}/{tenant}{path}
 */
export const workdayRoutes = [
	{
		key: 'createBusinessTitleChange',
		group: 'business',
		name: 'createBusinessTitleChange',
		method: 'POST',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/businessTitleChanges',
		description:
			'Creates a business title change for a worker (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
	{
		key: 'getBusinessTitleChange',
		group: 'business',
		name: 'getBusinessTitleChange',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/businessTitleChanges/{ID}',
		description:
			'Retrieves a business title change instance by ID (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getBusinessTitleChangeForWorker',
		group: 'business',
		name: 'getBusinessTitleChangeForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/businessTitleChanges/{subresourceID}',
		description:
			'Retrieves a business title change for a specific worker (Common API v1).',
		pathParams: ['ID', 'subresourceID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'createJobChange',
		group: 'job',
		name: 'createJobChange',
		method: 'POST',
		service: 'staffing',
		version: 'v6',
		path: '/workers/{ID}/jobChanges',
		description: 'Initiates a job change for a worker (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
	{
		key: 'getJobById',
		group: 'job',
		name: 'getJobById',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/jobs/{ID}',
		description: 'Retrieves a single job instance by ID (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangeFrequencies',
		group: 'job',
		name: 'getJobChangeFrequencies',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/frequencies',
		description:
			'Retrieves frequency prompt values for job changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangeLocationInfo',
		group: 'job',
		name: 'getJobChangeLocationInfo',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/jobChanges/{ID}/location',
		description: 'Retrieves location info for a job change (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangePosition',
		group: 'job',
		name: 'getJobChangePosition',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/jobChanges/{ID}/position',
		description: 'Retrieves position details for a job change (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangeReasonInstance',
		group: 'job',
		name: 'getJobChangeReasonInstance',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/reason/{ID}',
		description: 'Retrieves a job change reason instance (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangeReasonValues',
		group: 'job',
		name: 'getJobChangeReasonValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/reason',
		description: 'Retrieves job change reason prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangeReasons',
		group: 'job',
		name: 'getJobChangeReasons',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/reason',
		description: 'Retrieves job change reasons collection (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangesGroupTemplates',
		group: 'job',
		name: 'getJobChangesGroupTemplates',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/templates',
		description: 'Retrieves job change templates (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangesJobValues',
		group: 'job',
		name: 'getJobChangesJobValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/jobs',
		description: 'Retrieves job prompt values for job changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: ['effectiveDate', 'worker', 'limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobChangesWorkerValues',
		group: 'job',
		name: 'getJobChangesWorkerValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/workers',
		description:
			'Retrieves worker prompt values for job changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: ['effectiveDate', 'limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobClassifications',
		group: 'job',
		name: 'getJobClassifications',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/jobClassifications',
		description: 'Retrieves job classification prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobPosting',
		group: 'job',
		name: 'getJobPosting',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/jobPostings/{ID}',
		description:
			'Retrieves a job posting including description (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobPostingQuestionnaire',
		group: 'job',
		name: 'getJobPostingQuestionnaire',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/jobPostings/{ID}/questionnaires',
		description: 'Retrieves questionnaires for a job posting (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobProfilesValues',
		group: 'job',
		name: 'getJobProfilesValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/jobProfiles',
		description: 'Retrieves job profile prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobRequisitionValues',
		group: 'job',
		name: 'getJobRequisitionValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/jobRequisitions',
		description: 'Retrieves job requisition prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobWorkspace',
		group: 'job',
		name: 'getJobWorkspace',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/jobs/{ID}/workspace/{subresourceID}',
		description: 'Retrieves a workspace for a job (Staffing v6).',
		pathParams: ['ID', 'subresourceID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getJobWorkspaces',
		group: 'job',
		name: 'getJobWorkspaces',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/jobs/{ID}/workspace',
		description: 'Retrieves workspaces for a job (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'listJobPostings',
		group: 'job',
		name: 'listJobPostings',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/jobPostings',
		description: 'Lists job postings (Recruiting v4).',
		pathParams: [] as const,
		queryParams: [
			'limit',
			'offset',
			'jobRequisition',
			'category',
			'id',
			'jobSite',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'updateJobChangeBusinessTitle',
		group: 'job',
		name: 'updateJobChangeBusinessTitle',
		method: 'PATCH',
		service: 'staffing',
		version: 'v6',
		path: '/jobChanges/{ID}/businessTitle/{subresourceID}',
		description:
			'Partially updates business title on a job change (Staffing v6).',
		pathParams: ['ID', 'subresourceID'] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
	{
		key: 'createPayrollInputs',
		group: 'payroll',
		name: 'createPayrollInputs',
		method: 'POST',
		service: 'payroll',
		version: 'v1',
		path: '/payrollInputs',
		description: 'Creates payroll inputs (Payroll v1).',
		pathParams: [] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
	{
		key: 'getPayrollInputInstance',
		group: 'payroll',
		name: 'getPayrollInputInstance',
		method: 'GET',
		service: 'payroll',
		version: 'v1',
		path: '/payrollInputs/{ID}',
		description: 'Retrieves a payroll input by ID (Payroll v1).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'updateAnExistingPayroll',
		group: 'payroll',
		name: 'updateAnExistingPayroll',
		method: 'PATCH',
		service: 'payroll',
		version: 'v1',
		path: '/payrollInputs/{ID}',
		description: 'Partially updates a payroll input (Payroll v1).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
	{
		key: 'getCollectionOfPayroll',
		group: 'collection',
		name: 'getCollectionOfPayroll',
		method: 'GET',
		service: 'payroll',
		version: 'v1',
		path: '/payrollInputs',
		description: 'Retrieves a collection of payroll inputs (Payroll v1).',
		pathParams: [] as const,
		queryParams: [
			'limit',
			'offset',
			'startDate',
			'endDate',
			'worker',
			'payComponent',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'createTimeOffRequest',
		group: 'time',
		name: 'createTimeOffRequest',
		method: 'POST',
		service: 'absenceManagement',
		version: 'v5',
		path: '/workers/{ID}/requestTimeOff',
		description: 'Creates a time off request (Absence Management v5).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
	{
		key: 'getTimeOffEntriesForWorker',
		group: 'time',
		name: 'getTimeOffEntriesForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/timeOffEntries',
		description: 'Retrieves time off entries for a worker (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getTimeOffPlansForWorker',
		group: 'time',
		name: 'getTimeOffPlansForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/timeOffPlans',
		description: 'Retrieves time off plans for a worker (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getTimeOffStatusValues',
		group: 'time',
		name: 'getTimeOffStatusValues',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/values/timeOff/status',
		description:
			'Retrieves time off status prompt values (Absence Management v5).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getTimeTypes',
		group: 'time',
		name: 'getTimeTypes',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/timeTypes',
		description: 'Retrieves time type prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getAbsenceBalance',
		group: 'absence',
		name: 'getAbsenceBalance',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/balances/{ID}',
		description: 'Retrieves an absence balance by ID (Absence Management v5).',
		pathParams: ['ID'] as const,
		queryParams: ['worker', 'absencePlan', 'effective'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'listBalances',
		group: 'balances',
		name: 'listBalances',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/balances',
		description: 'Lists absence balances (Absence Management v5).',
		pathParams: [] as const,
		queryParams: [
			'limit',
			'offset',
			'worker',
			'category',
			'effective',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getAssignmentChangeGroupCostCenters',
		group: 'assignment',
		name: 'getAssignmentChangeGroupCostCenters',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/costCenters',
		description:
			'Retrieves cost center prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getAssignmentChangeGroupJobs',
		group: 'assignment',
		name: 'getAssignmentChangeGroupJobs',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/jobs',
		description:
			'Retrieves job prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getAssignmentTypes',
		group: 'assignment',
		name: 'getAssignmentTypes',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/assignmentTypes',
		description: 'Retrieves assignment type prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getCandidateAvailabilityTemplate',
		group: 'candidate',
		name: 'getCandidateAvailabilityTemplate',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/jobPostings/{ID}/candidateAvailabilityTemplate',
		description:
			'Retrieves candidate availability template for a job posting (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getCollectionOfJobs',
		group: 'collection',
		name: 'getCollectionOfJobs',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		// JobsApi.getCollection — only limit/offset (includeTerminatedWorkers is /workers).
		path: '/jobs',
		description:
			'Retrieves a paginated collection of jobs (Staffing v6 JobsApi.getCollection).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getCompanyInsiderTypes',
		group: 'company',
		name: 'getCompanyInsiderTypes',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/companyInsiderTypes',
		description: 'Retrieves company insider type prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getContingentWorkerTypes',
		group: 'contingent',
		name: 'getContingentWorkerTypes',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/contingentWorkerTypes',
		description:
			'Retrieves contingent worker type prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getCountryInfo',
		group: 'country',
		name: 'getCountryInfo',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/countries/{ID}',
		description: 'Retrieves country info (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getCurrencies',
		group: 'currencies',
		name: 'getCurrencies',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/currencies',
		description:
			'Retrieves currency prompt values for job changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getCurrentUser',
		group: 'current',
		name: 'getCurrentUser',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/workers/me',
		description: 'Retrieves the authenticated worker profile (Staffing v6).',
		pathParams: [] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getGrants',
		group: 'grants',
		name: 'getGrants',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/grants',
		description:
			'Retrieves grant prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getHeadcountOptions',
		group: 'headcount',
		name: 'getHeadcountOptions',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/headcountOptions',
		description: 'Retrieves headcount option prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getHistoryInstanceForWorker',
		group: 'history',
		name: 'getHistoryInstanceForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/history/{subresourceID}',
		description: 'Retrieves a history instance for a worker (Common API v1).',
		pathParams: ['ID', 'subresourceID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getHistoryItemsForWorker',
		group: 'history',
		name: 'getHistoryItemsForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/history',
		description: 'Retrieves history items for a worker (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getHolidayEvents',
		group: 'holiday',
		name: 'getHolidayEvents',
		method: 'GET',
		service: 'person',
		version: 'v4',
		path: '/holidayEvents',
		description:
			'Retrieves holiday events for workers/time period (Person v4).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset', 'fromDate', 'toDate', 'worker'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getInterview',
		group: 'interview',
		name: 'getInterview',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/interviews/{ID}',
		description: 'Retrieves an interview by ID (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getInterviewFeedback2',
		group: 'interview',
		name: 'getInterviewFeedback2',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/interviews/{ID}/feedback',
		description: 'Retrieves interview feedback (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getLeaveStatusValues',
		group: 'leave',
		name: 'getLeaveStatusValues',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/values/leave/status',
		description:
			'Retrieves leave status prompt values (Absence Management v5).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getMyJobPostings',
		group: 'my',
		name: 'getMyJobPostings',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		// REST entry: Recruiting v4 GET /jobRequisitions (not identical to /jobPostings).
		path: '/jobRequisitions',
		description: 'Lists job requisitions (Recruiting v4 GET /jobRequisitions).',
		pathParams: [] as const,
		queryParams: [
			'limit',
			'offset',
			'status',
			'supervisoryOrganization',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizationAssignmentBusinessUnits',
		group: 'organization',
		name: 'getOrganizationAssignmentBusinessUnits',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/businessUnits',
		description:
			'Retrieves business unit prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizationAssignmentCustoms',
		group: 'organization',
		name: 'getOrganizationAssignmentCustoms',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/customs',
		description: 'Retrieves custom org assignment prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizationAssignmentFunds',
		group: 'organization',
		name: 'getOrganizationAssignmentFunds',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/funds',
		description:
			'Retrieves fund prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizationAssignmentRegions',
		group: 'organization',
		name: 'getOrganizationAssignmentRegions',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/regions',
		description:
			'Retrieves region prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getOrganizationAssignmentWorkers',
		group: 'organization',
		name: 'getOrganizationAssignmentWorkers',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/organizationAssignmentChangesGroup/workers',
		description:
			'Retrieves worker prompt values for org assignment changes (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'organizationType',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getPayGroupByJobId',
		group: 'pay',
		name: 'getPayGroupByJobId',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/jobs/{ID}/payGroup',
		description: 'Retrieves the pay group for a job (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getPaySlipInstancesForWorker',
		group: 'pay',
		name: 'getPaySlipInstancesForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/paySlips/{subresourceID}',
		description: 'Retrieves a pay slip instance for a worker (Common API v1).',
		pathParams: ['ID', 'subresourceID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getPaySlipsForWorker',
		group: 'pay',
		name: 'getPaySlipsForWorker',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/paySlips',
		description: 'Retrieves pay slips for a worker (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getProposedPositionValues',
		group: 'proposed',
		name: 'getProposedPositionValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/proposedPosition',
		description: 'Retrieves proposed position prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getProspect',
		group: 'prospect',
		name: 'getProspect',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/prospects/{ID}',
		description: 'Retrieves a prospect (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getProspectEducations',
		group: 'prospect',
		name: 'getProspectEducations',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/prospects/{ID}/educations',
		description: 'Retrieves prospect educations (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getProspectExperiences',
		group: 'prospect',
		name: 'getProspectExperiences',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/prospects/{ID}/experiences',
		description: 'Retrieves prospect experiences (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getProspectResumeAttachments',
		group: 'prospect',
		name: 'getProspectResumeAttachments',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/prospects/{ID}/resumeAttachments',
		description: 'Retrieves prospect resume attachments (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getProspectSkills',
		group: 'prospect',
		name: 'getProspectSkills',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/prospects/{ID}/skills',
		description: 'Retrieves prospect skills (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getSupervisoryOrgValues',
		group: 'supervisory',
		name: 'getSupervisoryOrgValues',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/supervisoryOrganization',
		description:
			'Retrieves supervisory organization prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkStudyAwards',
		group: 'work',
		name: 'getWorkStudyAwards',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/workStudyAwards',
		description: 'Retrieves work study award prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerBusinessTitleChanges',
		group: 'worker',
		name: 'getWorkerBusinessTitleChanges',
		method: 'GET',
		service: 'common',
		version: 'v1',
		path: '/workers/{ID}/businessTitleChanges',
		description:
			'Retrieves business title changes for a worker (Common API v1).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerEligibleAbsenceTypes',
		group: 'worker',
		name: 'getWorkerEligibleAbsenceTypes',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/workers/{ID}/eligibleAbsenceTypes',
		description:
			'Retrieves eligible absence types for a worker (Absence Management v5).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset', 'effective'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerInfo',
		group: 'worker',
		name: 'getWorkerInfo',
		method: 'GET',
		// Alias of Staffing WorkersApi.getStaffingInformation (same as
		// getWorkerStaffingInformation). Workday docs do not expose a separate path.
		service: 'staffing',
		version: 'v6',
		path: '/workers/{ID}',
		description:
			'Retrieves worker staffing profile (Staffing v6 GET /workers/{ID}).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerLeavesOfAbsence',
		group: 'worker',
		name: 'getWorkerLeavesOfAbsence',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/workers/{ID}/leavesOfAbsence',
		description:
			'Retrieves leaves of absence for a worker (Absence Management v5).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset', 'fromDate', 'toDate', 'status'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerServiceDates',
		group: 'worker',
		name: 'getWorkerServiceDates',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/workers/{ID}/serviceDates',
		description: 'Retrieves service dates for a worker (Staffing v6).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerStaffingInformation',
		group: 'worker',
		name: 'getWorkerStaffingInformation',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		// WorkersApi.getStaffingInformation
		path: '/workers/{ID}',
		description:
			'Retrieves current staffing information for a worker (Staffing v6 WorkersApi.getStaffingInformation).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerTimeOffDetails',
		group: 'worker',
		name: 'getWorkerTimeOffDetails',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/workers/{ID}/timeOffDetails',
		description:
			'Retrieves time off details for a worker (Absence Management v5).',
		pathParams: ['ID'] as const,
		queryParams: ['limit', 'offset', 'fromDate', 'toDate'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerTypes',
		group: 'worker',
		name: 'getWorkerTypes',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/workerTypes',
		description: 'Retrieves worker type prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkerValidTimeOffDates',
		group: 'worker',
		name: 'getWorkerValidTimeOffDates',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/workers/{ID}/validTimeOffDates',
		description:
			'Retrieves valid time off dates for a worker (Absence Management v5).',
		pathParams: ['ID'] as const,
		queryParams: [
			'fromDate',
			'toDate',
			'timeOffType',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'retrieveWorkerLeaveOfAbsenceSubresource',
		group: 'worker',
		name: 'retrieveWorkerLeaveOfAbsenceSubresource',
		method: 'GET',
		service: 'absenceManagement',
		version: 'v5',
		path: '/workers/{ID}/leavesOfAbsence/{subresourceID}',
		description:
			'Retrieves a leave of absence subresource (Absence Management v5).',
		pathParams: ['ID', 'subresourceID'] as const,
		queryParams: [] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkersCollectionStaffing',
		group: 'workers',
		name: 'getWorkersCollectionStaffing',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/workers',
		description: 'Retrieves workers with staffing information (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'limit',
			'offset',
			'includeTerminatedWorkers',
			'search',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'getWorkspaceInstances',
		group: 'workspace',
		name: 'getWorkspaceInstances',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		path: '/values/jobChangesGroup/workSpaces',
		description: 'Retrieves workspace prompt values (Staffing v6).',
		pathParams: [] as const,
		queryParams: [
			'effectiveDate',
			'event',
			'job',
			'location',
			'manager',
			'staffingEvent',
			'worker',
			'limit',
			'offset',
		] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'listCountries',
		group: 'countries',
		name: 'listCountries',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/values/jobPostingsGroup/countries',
		description: 'Retrieves country values for recruiting (Recruiting v4).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'listInterviews',
		group: 'interviews',
		name: 'listInterviews',
		method: 'GET',
		service: 'recruiting',
		version: 'v4',
		path: '/interviews',
		description: 'Lists interviews (Recruiting v4).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset', 'status'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'listJobs',
		group: 'jobs',
		name: 'listJobs',
		method: 'GET',
		service: 'staffing',
		version: 'v6',
		// Alias of JobsApi.getCollection (same as getCollectionOfJobs).
		path: '/jobs',
		description: 'Lists jobs (Staffing v6 JobsApi.getCollection).',
		pathParams: [] as const,
		queryParams: ['limit', 'offset'] as const,
		riskLevel: 'read' as const,
	},
	{
		key: 'updateMessageTemplateById',
		group: 'message',
		name: 'updateMessageTemplateById',
		method: 'PUT',
		service: 'recruiting',
		version: 'v4',
		path: '/messageTemplates/{ID}',
		description: 'Updates a message template by ID (Recruiting v4).',
		pathParams: ['ID'] as const,
		queryParams: [] as const,
		riskLevel: 'write' as const,
	},
] as const satisfies readonly WorkdayRoute[];

export type WorkdayRouteName = (typeof workdayRoutes)[number]['name'];

export const workdayRouteByName = Object.fromEntries(
	workdayRoutes.map((r) => [r.name, r]),
) as { [K in WorkdayRouteName]: (typeof workdayRoutes)[number] };

export function getWorkdayRoute(name: WorkdayRouteName): WorkdayRoute {
	return workdayRouteByName[name];
}
