export type BrexHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';
export type BrexRisk = 'read' | 'write' | 'destructive';
export type BrexFilter =
	| 'transactionId'
	| 'transactionAmount'
	| 'transactionDescription'
	| 'cardStatus';

export type BrexRoute = {
	group: string;
	op: string;
	method: BrexHttpMethod;
	path: string;
	pathParams: readonly string[];
	queryParams: readonly string[];
	required: readonly string[];
	risk: BrexRisk;
	description: string;
	docs: string;
	filter?: BrexFilter;
	idempotency?: boolean;
};

const qPage = ['cursor', 'limit'] as const;

export const BREX_ROUTES = {
	usersList: {
		group: 'users',
		op: 'list',
		method: 'GET',
		path: '/v2/users',
		pathParams: [],
		queryParams: [...qPage, 'email'],
		required: [],
		risk: 'read',
		description: 'List users in the Brex account',
		docs: 'https://developer.brex.com/openapi/team_api/users/listusers',
	},
	usersCreate: {
		group: 'users',
		op: 'create',
		method: 'POST',
		path: '/v2/users',
		pathParams: [],
		queryParams: [],
		required: ['first_name', 'last_name', 'email'],
		risk: 'write',
		description: 'Invite a user as an employee',
		docs: 'https://developer.brex.com/openapi/team_api/users/createuser',
	},
	usersGetMe: {
		group: 'users',
		op: 'getMe',
		method: 'GET',
		path: '/v2/users/me',
		pathParams: [],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get the user for the current access token',
		docs: 'https://developer.brex.com/openapi/team_api/users/getme',
	},
	usersGet: {
		group: 'users',
		op: 'get',
		method: 'GET',
		path: '/v2/users/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a user by ID, or /me when id is "me"',
		docs: 'https://developer.brex.com/openapi/team_api/users/getuser',
	},
	usersUpdate: {
		group: 'users',
		op: 'update',
		method: 'PUT',
		path: '/v2/users/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a user; omitted fields stay unchanged',
		docs: 'https://developer.brex.com/openapi/team_api/users/updateuser',
	},
	usersGetLimit: {
		group: 'users',
		op: 'getLimit',
		method: 'GET',
		path: '/v2/users/{id}/limit',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get the monthly spend limit for a user',
		docs: 'https://developer.brex.com/openapi/team_api/users/getuserlimit',
	},
	usersSetLimit: {
		group: 'users',
		op: 'setLimit',
		method: 'POST',
		path: '/v2/users/{id}/limit',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Set monthly_limit in cents, or null to remove it',
		docs: 'https://developer.brex.com/openapi/team_api/users/setuserlimit',
	},
	locationsList: {
		group: 'locations',
		op: 'list',
		method: 'GET',
		path: '/v2/locations',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List locations',
		docs: 'https://developer.brex.com/openapi/team_api/locations/listlocations',
	},
	locationsCreate: {
		group: 'locations',
		op: 'create',
		method: 'POST',
		path: '/v2/locations',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a location',
		docs: 'https://developer.brex.com/openapi/team_api/locations/createlocation',
	},
	locationsGet: {
		group: 'locations',
		op: 'get',
		method: 'GET',
		path: '/v2/locations/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a location by ID',
		docs: 'https://developer.brex.com/openapi/team_api/locations/getlocation',
	},
	departmentsList: {
		group: 'departments',
		op: 'list',
		method: 'GET',
		path: '/v2/departments',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List departments',
		docs: 'https://developer.brex.com/openapi/team_api/departments/listdepartments',
	},
	departmentsCreate: {
		group: 'departments',
		op: 'create',
		method: 'POST',
		path: '/v2/departments',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a department',
		docs: 'https://developer.brex.com/openapi/team_api/departments/createdepartment',
	},
	departmentsGet: {
		group: 'departments',
		op: 'get',
		method: 'GET',
		path: '/v2/departments/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a department by ID',
		docs: 'https://developer.brex.com/openapi/team_api/departments/getdepartment',
	},
	titlesList: {
		group: 'titles',
		op: 'list',
		method: 'GET',
		path: '/v2/titles',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List job titles',
		docs: 'https://developer.brex.com/openapi/team_api/titles/listtitles',
	},
	titlesCreate: {
		group: 'titles',
		op: 'create',
		method: 'POST',
		path: '/v2/titles',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a job title',
		docs: 'https://developer.brex.com/openapi/team_api/titles/createtitle',
	},
	titlesGet: {
		group: 'titles',
		op: 'get',
		method: 'GET',
		path: '/v2/titles/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a job title by ID',
		docs: 'https://developer.brex.com/openapi/team_api/titles/gettitle',
	},
	cardsList: {
		group: 'cards',
		op: 'list',
		method: 'GET',
		path: '/v2/cards',
		pathParams: [],
		queryParams: [...qPage, 'user_id'],
		required: [],
		risk: 'read',
		description: 'List cards, optionally by user_id',
		docs: 'https://developer.brex.com/openapi/team_api/cards/listcards',
	},
	cardsCreate: {
		group: 'cards',
		op: 'create',
		method: 'POST',
		path: '/v2/cards',
		pathParams: [],
		queryParams: [],
		required: ['owner', 'card_name', 'card_type', 'limit_type'],
		risk: 'write',
		description: 'Create a card and assign it to a user',
		docs: 'https://developer.brex.com/openapi/team_api/cards/createcard',
		idempotency: true,
	},
	cardsGet: {
		group: 'cards',
		op: 'get',
		method: 'GET',
		path: '/v2/cards/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a card by ID',
		docs: 'https://developer.brex.com/openapi/team_api/cards/getcard',
	},
	cardsUpdate: {
		group: 'cards',
		op: 'update',
		method: 'PUT',
		path: '/v2/cards/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update card spend_controls for limit_type=CARD',
		docs: 'https://developer.brex.com/openapi/team_api/cards/updatecard',
	},
	cardsGetPan: {
		group: 'cards',
		op: 'getPan',
		method: 'GET',
		path: '/v2/cards/{id}/pan',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get card number, CVV, and expiration',
		docs: 'https://developer.brex.com/openapi/team_api/cards/getcardnumber',
	},
	cardsUpdateStatus: {
		group: 'cards',
		op: 'updateStatus',
		method: 'POST',
		path: '/v2/cards/{id}/{action}',
		pathParams: ['id'],
		queryParams: [],
		required: ['action'],
		risk: 'destructive',
		description: 'Lock, unlock, or terminate a card',
		docs: 'https://developer.brex.com/openapi/team_api/cards/lockcard',
		filter: 'cardStatus',
	},
	legalEntitiesList: {
		group: 'legalEntities',
		op: 'list',
		method: 'GET',
		path: '/v2/legal_entities',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List legal entities',
		docs: 'https://developer.brex.com/openapi/team_api/legal-entities/listlegalentities',
	},
	legalEntitiesGet: {
		group: 'legalEntities',
		op: 'get',
		method: 'GET',
		path: '/v2/legal_entities/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a legal entity by ID',
		docs: 'https://developer.brex.com/openapi/team_api/legal-entities/getlegalentity',
	},
	companyGet: {
		group: 'company',
		op: 'get',
		method: 'GET',
		path: '/v2/company',
		pathParams: [],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get the company for the current token',
		docs: 'https://developer.brex.com/openapi/team_api/companies/getcompany',
	},
	accountsListCard: {
		group: 'accounts',
		op: 'listCard',
		method: 'GET',
		path: '/v2/accounts/card',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List card accounts',
		docs: 'https://developer.brex.com/openapi/transactions_api/accounts/listcardaccounts',
	},
	accountsListCardStatements: {
		group: 'accounts',
		op: 'listCardStatements',
		method: 'GET',
		path: '/v2/accounts/card/primary/statements',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List finalized primary card statements',
		docs: 'https://developer.brex.com/openapi/transactions_api/accounts/listcardstatements',
	},
	accountsListCash: {
		group: 'accounts',
		op: 'listCash',
		method: 'GET',
		path: '/v2/accounts/cash',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List cash deposit accounts',
		docs: 'https://developer.brex.com/openapi/transactions_api/accounts/listcashaccounts',
	},
	accountsGetCashPrimary: {
		group: 'accounts',
		op: 'getCashPrimary',
		method: 'GET',
		path: '/v2/accounts/cash/primary',
		pathParams: [],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get the primary cash account',
		docs: 'https://developer.brex.com/openapi/transactions_api/accounts/getprimarycashaccount',
	},
	accountsGetCash: {
		group: 'accounts',
		op: 'getCash',
		method: 'GET',
		path: '/v2/accounts/cash/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a cash account by ID',
		docs: 'https://developer.brex.com/openapi/transactions_api/accounts/getcashaccount',
	},
	accountsListCashStatements: {
		group: 'accounts',
		op: 'listCashStatements',
		method: 'GET',
		path: '/v2/accounts/cash/{id}/statements',
		pathParams: ['id'],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List finalized cash account statements',
		docs: 'https://developer.brex.com/openapi/transactions_api/accounts/listcashstatements',
	},
	transactionsList: {
		group: 'transactions',
		op: 'list',
		method: 'GET',
		path: '/v2/transactions/card/primary',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description:
			'List settled card transactions. Date filters are client-side after paging.',
		docs: 'https://developer.brex.com/openapi/transactions_api/transactions/listcardtransactions',
	},
	transactionsGetById: {
		group: 'transactions',
		op: 'getById',
		method: 'GET',
		path: '/v2/transactions/card/primary',
		pathParams: [],
		queryParams: [...qPage],
		required: ['id'],
		risk: 'read',
		description:
			'Find a settled card transaction by ID by paging official list results',
		docs: 'https://developer.brex.com/openapi/transactions_api/transactions/listcardtransactions',
		filter: 'transactionId',
	},
	transactionsByAmountRange: {
		group: 'transactions',
		op: 'byAmountRange',
		method: 'GET',
		path: '/v2/transactions/card/primary',
		pathParams: [],
		queryParams: [...qPage],
		required: ['min_amount', 'max_amount'],
		risk: 'read',
		description:
			'Filter settled card transactions by USD amount after official paging',
		docs: 'https://developer.brex.com/openapi/transactions_api/transactions/listcardtransactions',
		filter: 'transactionAmount',
	},
	transactionsByDescription: {
		group: 'transactions',
		op: 'byDescription',
		method: 'GET',
		path: '/v2/transactions/card/primary',
		pathParams: [],
		queryParams: [...qPage],
		required: ['description'],
		risk: 'read',
		description:
			'Filter settled card transactions by description after official paging',
		docs: 'https://developer.brex.com/openapi/transactions_api/transactions/listcardtransactions',
		filter: 'transactionDescription',
	},
	expensesList: {
		group: 'expenses',
		op: 'list',
		method: 'GET',
		path: '/v1/expenses',
		pathParams: [],
		queryParams: [
			...qPage,
			'user_id',
			'budget_id',
			'status',
			'purchased_at_start',
			'purchased_at_end',
			'payment_posted_at_start',
			'payment_posted_at_end',
		],
		required: [],
		risk: 'read',
		description: 'List expenses',
		docs: 'https://developer.brex.com/openapi/expenses_api/expenses/listexpenses',
	},
	expensesGet: {
		group: 'expenses',
		op: 'get',
		method: 'GET',
		path: '/v1/expenses/{id}',
		pathParams: ['id'],
		queryParams: ['expand[]'],
		required: [],
		risk: 'read',
		description: 'Get an expense by ID',
		docs: 'https://developer.brex.com/openapi/expenses_api/expenses/getexpense',
	},
	expensesGetCard: {
		group: 'expenses',
		op: 'getCard',
		method: 'GET',
		path: '/v1/expenses/card/{expense_id}',
		pathParams: ['expense_id'],
		queryParams: ['expand[]'],
		required: [],
		risk: 'read',
		description: 'Get a card expense (deprecated official path)',
		docs: 'https://developer.brex.com/openapi/expenses_api/card-expenses/getcardexpense',
	},
	expensesUpdate: {
		group: 'expenses',
		op: 'update',
		method: 'PUT',
		path: '/v1/expenses/card/{expense_id}',
		pathParams: ['expense_id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a card expense',
		docs: 'https://developer.brex.com/openapi/expenses_api/card-expenses/updateexpense',
	},
	expensesListByBudget: {
		group: 'expenses',
		op: 'listByBudget',
		method: 'GET',
		path: '/v1/expenses',
		pathParams: [],
		queryParams: [...qPage, 'payment_posted_at_start', 'payment_posted_at_end'],
		required: ['budget_id'],
		risk: 'read',
		description: 'List expenses for a budget_id',
		docs: 'https://developer.brex.com/openapi/expenses_api/expenses/listexpenses',
	},
	receiptsMatch: {
		group: 'receipts',
		op: 'match',
		method: 'POST',
		path: '/v1/expenses/card/receipt_match',
		pathParams: [],
		queryParams: [],
		required: ['receipt_name'],
		risk: 'write',
		description: 'Create a receipt-match upload URI',
		docs: 'https://developer.brex.com/openapi/expenses_api/receipt-match/receiptmatch',
	},
	receiptsUpload: {
		group: 'receipts',
		op: 'upload',
		method: 'POST',
		path: '/v1/expenses/card/{expense_id}/receipt_upload',
		pathParams: ['expense_id'],
		queryParams: [],
		required: ['receipt_name'],
		risk: 'write',
		description: 'Create a receipt upload URI for a card expense',
		docs: 'https://developer.brex.com/openapi/expenses_api/receipt-upload/receiptupload',
	},
	budgetsList: {
		group: 'budgets',
		op: 'list',
		method: 'GET',
		path: '/v2/budgets',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List budgets',
		docs: 'https://developer.brex.com/openapi/budgets_api/budgets/listspendbudgets',
	},
	budgetsCreate: {
		group: 'budgets',
		op: 'create',
		method: 'POST',
		path: '/v2/budgets',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a budget',
		docs: 'https://developer.brex.com/openapi/budgets_api/budgets/createspendbudget',
	},
	budgetsGet: {
		group: 'budgets',
		op: 'get',
		method: 'GET',
		path: '/v2/budgets/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a budget by ID',
		docs: 'https://developer.brex.com/openapi/budgets_api/budgets/getspendbudgetbyid',
	},
	budgetsUpdate: {
		group: 'budgets',
		op: 'update',
		method: 'PUT',
		path: '/v2/budgets/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a budget',
		docs: 'https://developer.brex.com/openapi/budgets_api/budgets/updatespendbudget',
	},
	budgetsArchive: {
		group: 'budgets',
		op: 'archive',
		method: 'POST',
		path: '/v2/budgets/{id}/archive',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'destructive',
		description: 'Archive a budget',
		docs: 'https://developer.brex.com/openapi/budgets_api/budgets/archivespendbudget',
	},
	spendLimitsList: {
		group: 'spendLimits',
		op: 'list',
		method: 'GET',
		path: '/v2/spend_limits',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List spend limits',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v2)/listspendlimits',
	},
	spendLimitsCreate: {
		group: 'spendLimits',
		op: 'create',
		method: 'POST',
		path: '/v2/spend_limits',
		pathParams: [],
		queryParams: [],
		required: ['expense_policy_id', 'authorization_settings'],
		risk: 'write',
		description: 'Create a spend limit',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v2)/createspendlimit',
	},
	spendLimitsGet: {
		group: 'spendLimits',
		op: 'get',
		method: 'GET',
		path: '/v2/spend_limits/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a spend limit by ID',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v2)/getspendlimitbyid',
	},
	spendLimitsUpdate: {
		group: 'spendLimits',
		op: 'update',
		method: 'PUT',
		path: '/v2/spend_limits/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a spend limit',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v2)/updatespendlimit',
	},
	spendLimitsArchive: {
		group: 'spendLimits',
		op: 'archive',
		method: 'POST',
		path: '/v2/spend_limits/{id}/archive',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'destructive',
		description: 'Archive a spend limit',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v2)/archivespendlimit',
	},
	spendLimitsV1Create: {
		group: 'spendLimitsV1',
		op: 'create',
		method: 'POST',
		path: '/v1/budgets',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a v1 spend limit (legacy /v1/budgets)',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v1)/createspendlimit',
	},
	spendLimitsV1Update: {
		group: 'spendLimitsV1',
		op: 'update',
		method: 'PUT',
		path: '/v1/budgets/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a v1 spend limit (legacy /v1/budgets)',
		docs: 'https://developer.brex.com/openapi/budgets_api/spend-limits-(v1)/updatespendlimit',
	},
	budgetProgramsList: {
		group: 'budgetPrograms',
		op: 'list',
		method: 'GET',
		path: '/v1/budget_programs',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List budget programs',
		docs: 'https://developer.brex.com/openapi/budgets_api/budget-programs/listbudgetprograms',
	},
	vendorsList: {
		group: 'vendors',
		op: 'list',
		method: 'GET',
		path: '/v1/vendors',
		pathParams: [],
		queryParams: [...qPage, 'name'],
		required: [],
		risk: 'read',
		description: 'List vendors',
		docs: 'https://developer.brex.com/openapi/payments_api/vendors/listvendors',
	},
	vendorsCreate: {
		group: 'vendors',
		op: 'create',
		method: 'POST',
		path: '/v1/vendors',
		pathParams: [],
		queryParams: [],
		required: ['company_name'],
		risk: 'write',
		description: 'Create a vendor',
		docs: 'https://developer.brex.com/openapi/payments_api/vendors/createvendor',
	},
	vendorsGet: {
		group: 'vendors',
		op: 'get',
		method: 'GET',
		path: '/v1/vendors/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a vendor by ID',
		docs: 'https://developer.brex.com/openapi/payments_api/vendors/getvendor',
	},
	vendorsUpdate: {
		group: 'vendors',
		op: 'update',
		method: 'PUT',
		path: '/v1/vendors/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a vendor',
		docs: 'https://developer.brex.com/openapi/payments_api/vendors/updatevendor',
	},
	vendorsDelete: {
		group: 'vendors',
		op: 'delete',
		method: 'DELETE',
		path: '/v1/vendors/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'destructive',
		description: 'Delete a vendor',
		docs: 'https://developer.brex.com/openapi/payments_api/vendors/deletevendor',
	},
	transfersList: {
		group: 'transfers',
		op: 'list',
		method: 'GET',
		path: '/v1/transfers',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List transfers',
		docs: 'https://developer.brex.com/openapi/payments_api/transfers/listtransfers',
	},
	referralsList: {
		group: 'referrals',
		op: 'list',
		method: 'GET',
		path: '/v1/referrals',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List active referrals',
		docs: 'https://developer.brex.com/openapi/onboarding_api/referrals/listreferrals',
	},
	referralsCreate: {
		group: 'referrals',
		op: 'create',
		method: 'POST',
		path: '/v1/referrals',
		pathParams: [],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Create a referral and application link',
		docs: 'https://developer.brex.com/openapi/onboarding_api/referrals/createreferral',
	},
	referralsGet: {
		group: 'referrals',
		op: 'get',
		method: 'GET',
		path: '/v1/referrals/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a referral by ID',
		docs: 'https://developer.brex.com/openapi/onboarding_api/referrals/getreferral',
	},
	referralsCreateDocument: {
		group: 'referrals',
		op: 'createDocument',
		method: 'POST',
		path: '/v1/referrals/{id}/document_upload',
		pathParams: ['id'],
		queryParams: [],
		required: ['type'],
		risk: 'write',
		description: 'Create a referral document upload URI',
		docs: 'https://developer.brex.com/openapi/onboarding_api/referrals/createdocumentupload',
	},
	webhooksList: {
		group: 'webhooks',
		op: 'list',
		method: 'GET',
		path: '/v1/webhooks',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List webhook subscriptions',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-subscriptions/listwebhooks',
	},
	webhooksCreate: {
		group: 'webhooks',
		op: 'create',
		method: 'POST',
		path: '/v1/webhooks',
		pathParams: [],
		queryParams: [],
		required: ['url', 'event_types'],
		risk: 'write',
		description: 'Register a webhook subscription',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-subscriptions/registerwebhook',
	},
	webhooksGet: {
		group: 'webhooks',
		op: 'get',
		method: 'GET',
		path: '/v1/webhooks/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a webhook subscription',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-subscriptions/getwebhook',
	},
	webhooksUpdate: {
		group: 'webhooks',
		op: 'update',
		method: 'PUT',
		path: '/v1/webhooks/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a webhook subscription',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-subscriptions/updatewebhook',
	},
	webhooksListSecrets: {
		group: 'webhooks',
		op: 'listSecrets',
		method: 'GET',
		path: '/v1/webhooks/secrets',
		pathParams: [],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'List webhook signing secrets',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-subscriptions/listwebhooksecrets',
	},
	webhookGroupsList: {
		group: 'webhookGroups',
		op: 'list',
		method: 'GET',
		path: '/v1/webhooks/groups',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List webhook groups (partners)',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-groups/listwebhookgroups',
	},
	webhookGroupsCreate: {
		group: 'webhookGroups',
		op: 'create',
		method: 'POST',
		path: '/v1/webhooks/groups',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a webhook group (partners)',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-groups/createwebhookgroup',
	},
	webhookGroupsGet: {
		group: 'webhookGroups',
		op: 'get',
		method: 'GET',
		path: '/v1/webhooks/groups/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a webhook group (partners)',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-groups/getwebhookgroup',
	},
	webhookGroupsAddMembers: {
		group: 'webhookGroups',
		op: 'addMembers',
		method: 'POST',
		path: '/v1/webhooks/groups/{id}/add_members',
		pathParams: ['id'],
		queryParams: [],
		required: ['webhook_ids'],
		risk: 'write',
		description: 'Add webhook subscriptions to a group',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-groups/addwebhookgroupmembers',
	},
	webhookGroupsListMembers: {
		group: 'webhookGroups',
		op: 'listMembers',
		method: 'GET',
		path: '/v1/webhooks/groups/{id}/members',
		pathParams: ['id'],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List webhook group members',
		docs: 'https://developer.brex.com/openapi/webhooks_api/webhook-groups/listwebhookgroupmembers',
	},
	fieldsList: {
		group: 'fields',
		op: 'list',
		method: 'GET',
		path: '/v1/fields',
		pathParams: [],
		queryParams: [...qPage],
		required: [],
		risk: 'read',
		description: 'List custom fields',
		docs: 'https://developer.brex.com/openapi/fields_api/fields/listcustomfields',
	},
	fieldsCreate: {
		group: 'fields',
		op: 'create',
		method: 'POST',
		path: '/v1/fields',
		pathParams: [],
		queryParams: [],
		required: ['name'],
		risk: 'write',
		description: 'Create a custom field',
		docs: 'https://developer.brex.com/openapi/fields_api/fields/createacustomfield',
	},
	fieldsGet: {
		group: 'fields',
		op: 'get',
		method: 'GET',
		path: '/v1/fields/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a custom field by ID',
		docs: 'https://developer.brex.com/openapi/fields_api/fields/getcustomfield',
	},
	fieldsUpdate: {
		group: 'fields',
		op: 'update',
		method: 'PUT',
		path: '/v1/fields/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'write',
		description: 'Update a custom field',
		docs: 'https://developer.brex.com/openapi/fields_api/fields/updateacustomfield',
	},
	fieldsDelete: {
		group: 'fields',
		op: 'delete',
		method: 'DELETE',
		path: '/v1/fields/{id}',
		pathParams: ['id'],
		queryParams: [],
		required: [],
		risk: 'destructive',
		description: 'Delete a custom field',
		docs: 'https://developer.brex.com/openapi/fields_api/fields/deleteacustomfield',
	},
	fieldValuesList: {
		group: 'fieldValues',
		op: 'list',
		method: 'GET',
		path: '/v1/fields/{field_id}/values',
		pathParams: ['field_id'],
		queryParams: [...qPage, 'brex_id', 'value_id', 'remote_id', 'value'],
		required: [],
		risk: 'read',
		description: 'List values for a custom field',
		docs: 'https://developer.brex.com/openapi/fields_api/field-values/listcustomfieldvalues',
	},
	fieldValuesCreate: {
		group: 'fieldValues',
		op: 'create',
		method: 'POST',
		path: '/v1/fields/{field_id}/values',
		pathParams: ['field_id'],
		queryParams: [],
		required: ['values'],
		risk: 'write',
		description: 'Create custom field values (up to 1000)',
		docs: 'https://developer.brex.com/openapi/fields_api/field-values/createcustomfieldvalues',
	},
	fieldValuesUpdate: {
		group: 'fieldValues',
		op: 'update',
		method: 'PUT',
		path: '/v1/fields/{field_id}/values',
		pathParams: ['field_id'],
		queryParams: [],
		required: ['values'],
		risk: 'write',
		description: 'Update custom field values (up to 1000)',
		docs: 'https://developer.brex.com/openapi/fields_api/field-values/updatecustomfieldvalues',
	},
	fieldValuesDelete: {
		group: 'fieldValues',
		op: 'delete',
		method: 'DELETE',
		path: '/v1/fields/{field_id}/values',
		pathParams: ['field_id'],
		queryParams: [],
		required: ['values'],
		risk: 'destructive',
		description: 'Delete custom field values (up to 1000)',
		docs: 'https://developer.brex.com/openapi/fields_api/field-values/deletecustomfieldvalues',
	},
	fieldValuesGet: {
		group: 'fieldValues',
		op: 'get',
		method: 'GET',
		path: '/v1/fields/{field_id}/values/{brex_id}',
		pathParams: ['field_id', 'brex_id'],
		queryParams: [],
		required: [],
		risk: 'read',
		description: 'Get a field value by field ID and value ID',
		docs: 'https://developer.brex.com/openapi/fields_api/field-values/getafieldvalue',
	},
	tripsList: {
		group: 'trips',
		op: 'list',
		method: 'GET',
		path: '/v1/trips',
		pathParams: [],
		queryParams: [...qPage, 'user_id', 'starts_at_start', 'starts_at_end'],
		required: [],
		risk: 'read',
		description: 'List trips',
		docs: 'https://developer.brex.com/openapi/travel_api/trips/listtrips',
	},
} as const satisfies Record<string, BrexRoute>;

export type BrexRouteKey = keyof typeof BREX_ROUTES;

export function getBrexRoute(key: BrexRouteKey): BrexRoute {
	return BREX_ROUTES[key];
}

export const BREX_ROUTE_KEYS = Object.keys(BREX_ROUTES) as BrexRouteKey[];
