import type { EndpointRiskLevel } from 'corsair/core';

export type AlgoliaMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type AlgoliaHostType =
	| 'search'
	| 'analytics'
	| 'ingestion'
	| 'insights'
	| 'querySuggestions'
	| 'usage'
	| 'personalization';

export type AlgoliaRoute = {
	key: string;
	group: string;
	name: string;
	method: AlgoliaMethod;
	path: string;
	hostType: AlgoliaHostType;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const algoliaRoutes = [
	{
		key: 'addAbTest',
		group: 'abTests',
		name: 'addAbTest',
		method: 'POST',
		path: '/2/abtests',
		hostType: 'analytics',
		description:
			'Tool to create an A/B test comparing search performance between two index variants. Use when you need to test different search configurations, ranking strategies, or index settings and measure their impact on user behavior.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'addOrReplaceRecord',
		group: 'indices',
		name: 'addOrReplaceRecord',
		method: 'PUT',
		path: '/1/indexes/{indexName}/{objectID}',
		hostType: 'search',
		description:
			'Tool to add or replace a specific record in an index by objectID. If a record with the given objectID exists, it is replaced; otherwise, a new record is created. Use when you need to upsert an object with a known ID.',
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'addRecord',
		group: 'indices',
		name: 'addRecord',
		method: 'POST',
		path: '/1/indexes/{indexName}',
		hostType: 'search',
		description:
			'Tool to add a record to an index with auto-generated objectID. Records with matching IDs are replaced. Use when you need to insert a new object into an index.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'browseIndex',
		group: 'indices',
		name: 'browseIndex',
		method: 'POST',
		path: '/1/indexes/{indexName}/browse',
		hostType: 'search',
		description:
			'Tool to retrieve all records from an index. Use when you need to export or iterate through an entire index dataset.',
		pathParams: ['index_name'],
		queryParams: [],
		// POST body carries query/filters but the call is read-only (no
		// index mutation); classify as 'read' so read-only API keys can browse.
		riskLevel: 'read' as const,
	},
	{
		key: 'clearObjects',
		group: 'indices',
		name: 'clearObjects',
		method: 'POST',
		path: '/1/indexes/{indexName}/clear',
		hostType: 'search',
		description:
			'Tool to clear records of an index without affecting settings. Use when you need to completely wipe all objects (e.g., after a bulk reindex) while preserving index configuration.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'clearRules',
		group: 'rules',
		name: 'clearRules',
		method: 'POST',
		path: '/1/indexes/{indexName}/rules/clear',
		hostType: 'search',
		description:
			'Tool to delete all rules in an index. Use when you need to wipe all rules before re-creating them. Use after confirming no critical rules require retention.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'clearSynonyms',
		group: 'synonyms',
		name: 'clearSynonyms',
		method: 'POST',
		path: '/1/indexes/{indexName}/synonyms/clear',
		hostType: 'search',
		description:
			'Tool to delete all synonyms from an index. Use when you need to remove all synonym definitions in one operation.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'clickedObjectIds',
		group: 'insights',
		name: 'clickedObjectIds',
		method: 'POST',
		path: '/1/events',
		hostType: 'insights',
		description:
			'Tool to send a click event to Algolia to capture clicked items. Use immediately after a user click outside of search contexts to report click events.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'clickedObjectIdsAfterSearch',
		group: 'insights',
		name: 'clickedObjectIdsAfterSearch',
		method: 'POST',
		path: '/1/events',
		hostType: 'insights',
		description:
			'Tool to send a click event after a search response. Use when you want to report which items a user clicked in search results.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'computeRealtimeUser',
		group: 'personalization',
		name: 'computeRealtimeUser',
		method: 'POST',
		path: '/2/realtime/users/{userToken}/compute',
		hostType: 'personalization',
		description:
			"Tool to compute a user's real-time personalization profile in Algolia. Use when you need to trigger calculation of personalization data for a specific user. Note: This endpoint is deprecated.",
		pathParams: ['user_token'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'convertedObjectIds',
		group: 'insights',
		name: 'convertedObjectIds',
		method: 'POST',
		path: '/1/events',
		hostType: 'insights',
		description:
			'Tool to send a conversion event for items outside of search context. Use when tracking conversions on category pages or external flows unrelated to Algolia search.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'copyIndex',
		group: 'indices',
		name: 'copyIndex',
		method: 'POST',
		path: '/1/indexes/{indexName}/operation',
		hostType: 'search',
		description:
			'Tool to copy the specified index to a new index. Use when you need to duplicate an existing index including records, settings, synonyms, and rules after confirming source and destination names.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createApiKey',
		group: 'apiKeys',
		name: 'createApiKey',
		method: 'POST',
		path: '/1/keys',
		hostType: 'search',
		description:
			'Tool to create a new API key with specific permissions and restrictions. Use when you need to generate API keys with custom ACL permissions, index restrictions, rate limits, or expiration times.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createAuthentication',
		group: 'authentications',
		name: 'createAuthentication',
		method: 'POST',
		path: '/1/authentications',
		hostType: 'ingestion',
		description:
			'Tool to create a new authentication resource in Algolia. Use when you need to set up authentication credentials for connecting to sources or destinations in the Algolia ingestion API.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createDestination',
		group: 'destinations',
		name: 'createDestination',
		method: 'POST',
		path: '/1/destinations',
		hostType: 'ingestion',
		description:
			'Tool to create a new destination in Algolia Ingestion API. Use when you need to set up a new destination for data ingestion.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createIngestionTask',
		group: 'tasks',
		name: 'createIngestionTask',
		method: 'POST',
		path: '/2/tasks',
		hostType: 'ingestion',
		description:
			'Tool to create a new ingestion task connecting a source to a destination in Algolia. Use when you need to set up data synchronization between a source and an Algolia index.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createOrUpdateRecommendRules',
		group: 'rules',
		name: 'createOrUpdateRecommendRules',
		method: 'POST',
		path: '/1/indexes/{indexName}/{model}/recommend/rules/batch',
		hostType: 'search',
		description:
			'Tool to create or update a batch of Recommend Rules in an index. Use when you need to add or modify multiple rules at once for a recommendation model. Each rule is created or updated depending on whether a rule with the same objectID already exists.',
		pathParams: ['index_name', 'model'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createQsConfig',
		group: 'querySuggestions',
		name: 'createQsConfig',
		method: 'POST',
		path: '/1/configs',
		hostType: 'querySuggestions',
		description:
			'Tool to create a new Query Suggestions configuration for an Algolia index. Use when you need to set up query suggestions to help users discover popular searches. Up to 100 configurations per application are supported.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createSource',
		group: 'sources',
		name: 'createSource',
		method: 'POST',
		path: '/1/sources',
		hostType: 'ingestion',
		description:
			'Tool to create a new data source in Algolia Ingestion API. Use when you need to set up a new source for data ingestion from external platforms or custom data feeds.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'createTransformation',
		group: 'transformations',
		name: 'createTransformation',
		method: 'POST',
		path: '/1/transformations',
		hostType: 'ingestion',
		description:
			'Tool to create a new transformation in Algolia Ingestion API. Use when you need to set up data transformations for enriching or modifying records during ingestion.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'deleteAbTest',
		group: 'abTests',
		name: 'deleteAbTest',
		method: 'DELETE',
		path: '/2/abtests/{id}',
		hostType: 'analytics',
		description:
			'Tool to delete an A/B test by its unique identifier. Use when you need to permanently remove an A/B test configuration.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteApiKey',
		group: 'apiKeys',
		name: 'deleteApiKey',
		method: 'DELETE',
		path: '/1/keys/{key}',
		hostType: 'search',
		description:
			'Tool to delete an API key. Use when you need to revoke or remove an existing API key from your Algolia application.',
		pathParams: ['key'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteAuthentication',
		group: 'authentications',
		name: 'deleteAuthentication',
		method: 'DELETE',
		path: '/1/authentications/{authenticationID}',
		hostType: 'ingestion',
		description:
			'Tool to delete an authentication resource from Algolia. Use when you need to remove an existing authentication resource by its ID.',
		pathParams: ['authenticationID'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteConfig',
		group: 'querySuggestions',
		name: 'deleteConfig',
		method: 'DELETE',
		path: '/1/configs/{indexName}',
		hostType: 'querySuggestions',
		description:
			'Tool to delete a Query Suggestions configuration for the specified index. Use when you need to remove a Query Suggestions configuration permanently.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteDestination',
		group: 'destinations',
		name: 'deleteDestination',
		method: 'DELETE',
		path: '/1/destinations/{destinationID}',
		hostType: 'ingestion',
		description:
			'Tool to delete a destination in Algolia Ingestion API. Use when you need to permanently remove a destination by its ID.',
		pathParams: ['destination_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteIndex',
		group: 'indices',
		name: 'deleteIndex',
		method: 'DELETE',
		path: '/1/indexes/{indexName}',
		hostType: 'search',
		description:
			"Tool to delete the specified index and all its records. Use when you need to permanently remove an index after confirming it's no longer needed.",
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteObjects',
		group: 'indices',
		name: 'deleteObjects',
		method: 'POST',
		path: '/1/indexes/{indexName}/batch',
		hostType: 'search',
		description:
			'Tool to delete multiple records from an Algolia index. Use when you need to remove multiple objects by their IDs.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteRecommendRule',
		group: 'rules',
		name: 'deleteRecommendRule',
		method: 'DELETE',
		path: '/1/indexes/{indexName}/{model}/recommend/rules/{objectID}',
		hostType: 'search',
		description:
			"Tool to delete a Recommend rule from a recommendation scenario. Use when you need to remove a specific rule from an index's recommend model.",
		pathParams: ['index_name', 'model', 'object_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteRecordsByFilter',
		group: 'indices',
		name: 'deleteRecordsByFilter',
		method: 'POST',
		path: '/1/indexes/{indexName}/deleteByQuery',
		hostType: 'search',
		description:
			'Tool to delete records matching a filter from an Algolia index. Use when you need to remove multiple records based on filter criteria (e.g., category, tags, numeric ranges). This is a resource-intensive operation.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteRule',
		group: 'rules',
		name: 'deleteRule',
		method: 'DELETE',
		path: '/1/indexes/{indexName}/rules/{objectID}',
		hostType: 'search',
		description:
			'Tool to delete the specified rule from an index. Use when you need to permanently remove a rule after confirming its objectID.',
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteSource',
		group: 'sources',
		name: 'deleteSource',
		method: 'DELETE',
		path: '/1/sources/{sourceID}',
		hostType: 'ingestion',
		description:
			"Tool to delete a source from the Algolia Ingestion API. Use when you need to permanently remove a source after confirming it's no longer needed.",
		pathParams: ['sourceID'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteSynonym',
		group: 'synonyms',
		name: 'deleteSynonym',
		method: 'DELETE',
		path: '/1/indexes/{indexName}/synonyms/{objectID}',
		hostType: 'search',
		description:
			'Tool to delete a synonym from a specified index. Use when you need to remove an existing synonym by its objectID.',
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteTransformation',
		group: 'transformations',
		name: 'deleteTransformation',
		method: 'DELETE',
		path: '/1/transformations/{transformationID}',
		hostType: 'ingestion',
		description:
			'Tool to delete a transformation in Algolia Ingestion API. Use when you need to permanently remove a transformation by its ID.',
		pathParams: ['transformation_id'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteUserProfile',
		group: 'personalization',
		name: 'deleteUserProfile',
		method: 'DELETE',
		path: '/1/profiles/personalization/{userToken}',
		hostType: 'search',
		description:
			"Tool to delete a user profile from personalization. Use when you need to remove a user's personalization data and reset their profile.",
		pathParams: ['user_token'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'deleteUserToken',
		group: 'insights',
		name: 'deleteUserToken',
		method: 'DELETE',
		path: '/1/usertokens/{userToken}',
		hostType: 'insights',
		description:
			'Tool to delete all events related to a user token from events metrics and analytics. Use when removing user data from Algolia Insights.',
		pathParams: ['user_token'],
		queryParams: [],
		riskLevel: 'destructive' as const,
		irreversible: true,
	},
	{
		key: 'disableTaskV1',
		group: 'tasks',
		name: 'disableTaskV1',
		method: 'POST',
		path: '/1/tasks/{taskID}/disable',
		hostType: 'ingestion',
		description:
			'Tool to disable a task V1 in Algolia Ingestion API. Use when you need to disable a specific task. Note: This API is deprecated but still functional.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'enableTaskV1',
		group: 'tasks',
		name: 'enableTaskV1',
		method: 'POST',
		path: '/1/tasks/{taskID}/enable',
		hostType: 'ingestion',
		description:
			'Tool to enable a task V1 in Algolia Ingestion API. Use when you need to activate a previously disabled task. Note: This API is deprecated but still functional.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'executeBatchOnMultipleIndices',
		group: 'indices',
		name: 'executeBatchOnMultipleIndices',
		method: 'POST',
		path: '/1/indexes/*/batch',
		hostType: 'search',
		description:
			'Tool to perform batch operations (add, update, delete) across multiple Algolia indices in a single request. Use when you need to modify records in different indices efficiently. Each operation specifies its target index and action type.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'exportRules',
		group: 'rules',
		name: 'exportRules',
		method: 'POST',
		path: '/1/indexes/{indexName}/rules/search',
		hostType: 'search',
		description:
			'Tool to export all rules defined on an index. Use when you need to backup or migrate index rules.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'findObject',
		group: 'search',
		name: 'findObject',
		method: 'POST',
		path: '/1/indexes/{indexName}/query',
		hostType: 'search',
		description:
			'Tool to find the first object matching a query or filter in an index. Use when debugging relevance or filter logic after confirming index exists.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'getAbTest',
		group: 'abTests',
		name: 'getAbTest',
		method: 'GET',
		path: '/2/abtests/{id}',
		hostType: 'analytics',
		description:
			'Tool to retrieve detailed information about an A/B test by its ID. Use when you need to check A/B test status, performance metrics, or configuration details.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAddToCartRate',
		group: 'analytics',
		name: 'getAddToCartRate',
		method: 'GET',
		path: '/2/conversions/addToCartRate',
		hostType: 'analytics',
		description:
			'Tool to retrieve add-to-cart rate metrics for e-commerce search analytics. Use when you need to analyze conversion effectiveness and user purchasing behavior for an index, including daily breakdowns.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getApiKey',
		group: 'apiKeys',
		name: 'getApiKey',
		method: 'GET',
		path: '/1/keys/{key}',
		hostType: 'search',
		description:
			"Tool to retrieve the permissions and details of a specific API key. Use when you need to inspect an API key's ACL, restrictions, or other settings.",
		pathParams: ['key'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAppTask',
		group: 'tasks',
		name: 'getAppTask',
		method: 'GET',
		path: '/1/task/{taskID}',
		hostType: 'search',
		description:
			'Tool to check the status of an application task. Use when you need to verify if a task has completed.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAuthentication',
		group: 'authentications',
		name: 'getAuthentication',
		method: 'GET',
		path: '/1/authentications/{authenticationID}',
		hostType: 'ingestion',
		description:
			"Tool to retrieve an authentication resource by its ID. Use when you need to fetch details about a specific authentication configuration in Algolia's ingestion API.",
		pathParams: ['authentication_id'],
		queryParams: ['region'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getAverageClickPosition',
		group: 'analytics',
		name: 'getAverageClickPosition',
		method: 'GET',
		path: '/2/clicks/averageClickPosition',
		hostType: 'analytics',
		description:
			'Tool to retrieve average click position metrics from Algolia Analytics. Use when analyzing user engagement and click behavior for search results.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getClickPositions',
		group: 'analytics',
		name: 'getClickPositions',
		method: 'GET',
		path: '/2/clicks/positions',
		hostType: 'analytics',
		description:
			'Tool to retrieve the distribution of clicks by position from Algolia Analytics. Use when analyzing which search result positions receive the most user engagement.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getClickThroughRate',
		group: 'analytics',
		name: 'getClickThroughRate',
		method: 'GET',
		path: '/2/clicks/clickThroughRate',
		hostType: 'analytics',
		description:
			'Tool to retrieve click-through rate (CTR) for searches with at least one click event. Use when you need to analyze search effectiveness and user engagement metrics for an index, including daily breakdowns.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getConfig',
		group: 'querySuggestions',
		name: 'getConfig',
		method: 'GET',
		path: '/1/configs/{indexName}',
		hostType: 'querySuggestions',
		description:
			'Tool to retrieve a Query Suggestions configuration by index name. Use when you need to inspect or verify Query Suggestions settings for a specific index.',
		pathParams: ['indexName'],
		queryParams: ['region'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getConfig2',
		group: 'personalization',
		name: 'getConfig2',
		method: 'GET',
		path: '/2/config',
		hostType: 'personalization',
		description:
			'Tool to retrieve the advanced personalization configuration. Use when you need to check personalization settings, re-ranking impact levels, or profile types for your Algolia application. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getConversionRate',
		group: 'analytics',
		name: 'getConversionRate',
		method: 'GET',
		path: '/2/conversions/conversionRate',
		hostType: 'analytics',
		description:
			'Tool to retrieve conversion rate for searches with conversion events. Use when you need to analyze conversion effectiveness and user behavior metrics for an index, including daily breakdowns.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDestination',
		group: 'destinations',
		name: 'getDestination',
		method: 'GET',
		path: '/1/destinations/{destinationID}',
		hostType: 'ingestion',
		description:
			'Tool to retrieve a destination by its ID. Use when you need to get details about a specific Algolia destination resource.',
		pathParams: ['destinationID'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDictionaryLanguages',
		group: 'dictionaries',
		name: 'getDictionaryLanguages',
		method: 'GET',
		path: '/1/dictionaries/*/languages',
		hostType: 'search',
		description:
			'Tool to list available languages for dictionary entries. Use when you need to check which languages support custom dictionary entries (plurals, stopwords, compounds). #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getDictionarySettings',
		group: 'dictionaries',
		name: 'getDictionarySettings',
		method: 'GET',
		path: '/1/dictionaries/*/settings',
		hostType: 'search',
		description:
			'Tool to retrieve dictionary settings for all dictionaries. Use when you need to check which standard dictionary entries are disabled across different languages. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getLogs',
		group: 'logs',
		name: 'getLogs',
		method: 'GET',
		path: '/1/logs',
		hostType: 'search',
		description:
			'Tool to retrieve log entries for API requests made to your Algolia application. Use when you need to debug issues, monitor API usage, or analyze search patterns.',
		pathParams: [],
		queryParams: ['type', 'length', 'offset', 'indexName'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getNoClickRate',
		group: 'analytics',
		name: 'getNoClickRate',
		method: 'GET',
		path: '/2/searches/noClickRate',
		hostType: 'analytics',
		description:
			"Tool to retrieve the rate of searches that received no clicks. Use when you need to analyze search effectiveness and identify queries where users didn't engage with any results.",
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getNoResultsRate',
		group: 'analytics',
		name: 'getNoResultsRate',
		method: 'GET',
		path: '/2/searches/noResultRate',
		hostType: 'analytics',
		description:
			"Tool to retrieve the fraction of searches that didn't return any results. Use when you need to analyze search effectiveness and identify queries that fail to return results.",
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getNoResultsSearches',
		group: 'analytics',
		name: 'getNoResultsSearches',
		method: 'GET',
		path: '/2/searches/noResults',
		hostType: 'analytics',
		description:
			'Tool to retrieve the most frequent searches that produced zero results. Use when analyzing search gaps or identifying content opportunities to improve search experience.',
		pathParams: [],
		queryParams: ['tags', 'index', 'limit', 'offset', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getObjectPosition',
		group: 'search',
		name: 'getObjectPosition',
		method: 'POST',
		path: '/1/indexes/{indexName}/query',
		hostType: 'search',
		description:
			'Tool to retrieve an object’s position in a result set. Use when debugging relevance after performing a search query.',
		pathParams: ['indexName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'getObjects',
		group: 'search',
		name: 'getObjects',
		method: 'POST',
		path: '/1/indexes/*/objects',
		hostType: 'search',
		description:
			'Tool to retrieve multiple records from an index. Use when you need to batch-fetch several objectIDs in one call.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'getPurchaseRate',
		group: 'analytics',
		name: 'getPurchaseRate',
		method: 'GET',
		path: '/2/conversions/purchaseRate',
		hostType: 'analytics',
		description:
			'Tool to retrieve purchase rate metrics for searches that led to purchase events. Use when you need to analyze conversion effectiveness and purchase behavior for an index, including daily breakdowns.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getRecommendRule',
		group: 'rules',
		name: 'getRecommendRule',
		method: 'GET',
		path: '/1/indexes/{indexName}/{model}/recommend/rules/{objectID}',
		hostType: 'search',
		description:
			"Tool to retrieve a Recommend rule that was previously created in the Algolia dashboard. Use when you need to inspect a specific rule's configuration, conditions, or consequences by its objectID.",
		pathParams: ['index_name', 'model', 'object_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getRecommendTaskStatus',
		group: 'indices',
		name: 'getRecommendTaskStatus',
		method: 'GET',
		path: '/1/indexes/{indexName}/{model}/task/{taskID}',
		hostType: 'search',
		description:
			'Tool to check the status of a Recommend task. Use when you need to verify if an asynchronous Recommend operation (such as deleting a Recommend rule) has completed.',
		pathParams: ['index_name', 'model', 'task_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getRecord',
		group: 'indices',
		name: 'getRecord',
		method: 'GET',
		path: '/1/indexes/{indexName}/{objectID}',
		hostType: 'search',
		description:
			"Tool to retrieve a specific record from an index by its objectID. Use when you need to fetch a single object's details.",
		pathParams: ['index_name', 'object_id'],
		queryParams: ['attributes_to_retrieve'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getRevenue',
		group: 'analytics',
		name: 'getRevenue',
		method: 'GET',
		path: '/2/conversions/revenue',
		hostType: 'analytics',
		description:
			'Tool to retrieve revenue data from Algolia Analytics. Use when analyzing revenue metrics and conversion tracking for search results.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getRule',
		group: 'rules',
		name: 'getRule',
		method: 'GET',
		path: '/1/indexes/{indexName}/rules/{objectID}',
		hostType: 'search',
		description:
			"Tool to retrieve a specific rule by its objectID from an index. Use when you need to inspect a rule's configuration, conditions, and consequences.",
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSearchesCount',
		group: 'analytics',
		name: 'getSearchesCount',
		method: 'GET',
		path: '/2/searches/count',
		hostType: 'analytics',
		description:
			'Tool to retrieve the number of searches within a time range, including a daily breakdown. Use when analyzing search volume and traffic patterns for an index.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSearchesNoClicks',
		group: 'analytics',
		name: 'getSearchesNoClicks',
		method: 'GET',
		path: '/2/searches/noClicks',
		hostType: 'analytics',
		description:
			'Tool to retrieve top searches that did not receive any clicks. Use when analyzing search queries that may need optimization, such as queries with poor results or missing content.',
		pathParams: [],
		queryParams: ['tags', 'index', 'limit', 'offset', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSettings',
		group: 'indices',
		name: 'getSettings',
		method: 'GET',
		path: '/1/indexes/{indexName}/settings',
		hostType: 'search',
		description:
			'Tool to retrieve the settings of a specified index. Use when you need to inspect index configurations after creation or update.',
		pathParams: ['indexName'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSource',
		group: 'sources',
		name: 'getSource',
		method: 'GET',
		path: '/1/sources/{sourceID}',
		hostType: 'ingestion',
		description:
			'Tool to retrieve a source from the Algolia Ingestion API. Use when you need to get details about a specific data source by its ID.',
		pathParams: ['sourceID'],
		queryParams: ['region'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getSynonym',
		group: 'synonyms',
		name: 'getSynonym',
		method: 'GET',
		path: '/1/indexes/{indexName}/synonyms/{objectID}',
		hostType: 'search',
		description:
			'Tool to retrieve a specific synonym by its objectID. Use when you need to fetch details of an existing synonym from an index.',
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTaskStatus',
		group: 'indices',
		name: 'getTaskStatus',
		method: 'GET',
		path: '/1/indexes/{indexName}/task/{taskID}',
		hostType: 'search',
		description:
			'Tool to check the status of an asynchronous task. Use when you need to verify completion of operations like adding or deleting records.',
		pathParams: ['index_name', 'task_id'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTaskV1',
		group: 'tasks',
		name: 'getTaskV1',
		method: 'GET',
		path: '/1/tasks/{taskID}',
		hostType: 'ingestion',
		description:
			'Tool to retrieve a task V1 from Algolia Ingestion API. Use when you need to fetch details about a specific task. Note: This API is deprecated but still functional.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTopCountries',
		group: 'analytics',
		name: 'getTopCountries',
		method: 'GET',
		path: '/2/countries',
		hostType: 'analytics',
		description:
			'Tool to retrieve top countries by search volume for a specified index. Use when you need to analyze geographic distribution of searches and understand where your users are searching from.',
		pathParams: [],
		queryParams: ['tags', 'index', 'limit', 'offset', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTopFilterAttributes',
		group: 'analytics',
		name: 'getTopFilterAttributes',
		method: 'GET',
		path: '/2/filters',
		hostType: 'analytics',
		description:
			'Tool to retrieve top filter attributes from Algolia Analytics. Use when analyzing which filters are most commonly used by users in searches.',
		pathParams: [],
		queryParams: [
			'tags',
			'index',
			'limit',
			'offset',
			'search',
			'endDate',
			'startDate',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTopFilterForAttribute',
		group: 'analytics',
		name: 'getTopFilterForAttribute',
		method: 'GET',
		path: '/2/filters/{attribute}',
		hostType: 'analytics',
		description:
			'Tool to retrieve top filter values for a specific attribute from Algolia Analytics. Use when analyzing which filter values are most commonly used for a given attribute in search queries.',
		pathParams: ['attribute'],
		queryParams: [
			'tags',
			'index',
			'limit',
			'offset',
			'search',
			'endDate',
			'startDate',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTopFiltersNoResults',
		group: 'analytics',
		name: 'getTopFiltersNoResults',
		method: 'GET',
		path: '/2/filters/noResults',
		hostType: 'analytics',
		description:
			'Tool to retrieve top filters for searches that returned no results from Algolia Analytics. Use when analyzing which filters are commonly applied to searches that yield zero results, helping identify potential catalog or filtering issues.',
		pathParams: [],
		queryParams: [
			'tags',
			'index',
			'limit',
			'offset',
			'search',
			'endDate',
			'startDate',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTopHits',
		group: 'analytics',
		name: 'getTopHits',
		method: 'GET',
		path: '/2/hits',
		hostType: 'analytics',
		description:
			'Tool to retrieve the object IDs of the most frequent search results from Algolia Analytics. Returns up to 1,000 top hits ranked by frequency, optionally including click analytics (CTR, conversion rates) and revenue metrics. Use when analyzing which results appear most often in searches.',
		pathParams: [],
		queryParams: [
			'tags',
			'index',
			'limit',
			'offset',
			'search',
			'endDate',
			'startDate',
			'clickAnalytics',
			'revenueAnalytics',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTopSearches',
		group: 'analytics',
		name: 'getTopSearches',
		method: 'GET',
		path: '/2/searches',
		hostType: 'analytics',
		description:
			'Tool to retrieve the most popular searches from Algolia Analytics. Returns search queries ranked by frequency, optionally including click analytics (CTR, conversion rates) and revenue metrics. Use when analyzing search behavior and identifying trending queries.',
		pathParams: [],
		queryParams: [
			'tags',
			'index',
			'limit',
			'offset',
			'endDate',
			'orderBy',
			'direction',
			'startDate',
			'clickAnalytics',
			'revenueAnalytics',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getTransformation',
		group: 'transformations',
		name: 'getTransformation',
		method: 'GET',
		path: '/1/transformations/{transformationID}',
		hostType: 'ingestion',
		description:
			"Tool to retrieve a transformation by its ID from Algolia's Ingestion API. Use when you need to fetch details about a specific transformation including its code, configuration, and metadata.",
		pathParams: ['transformationID'],
		queryParams: ['region'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUsage',
		group: 'usage',
		name: 'getUsage',
		method: 'GET',
		path: '/1/usage/records',
		hostType: 'usage',
		description:
			'Tool to retrieve Algolia usage statistics over a specified time period. Use when you need to analyze search operations, indexing operations, capacity metrics, or other usage data for an Algolia application. Requires Premium plan or Enterprise add-on access.',
		pathParams: [],
		queryParams: ['endDate', 'startDate', 'statistic', 'granularity'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUsageForIndex',
		group: 'usage',
		name: 'getUsageForIndex',
		method: 'GET',
		path: '/1/usage/indices/{indexName}',
		hostType: 'usage',
		description:
			'Tool to retrieve usage statistics for a specific Algolia index over a time period. Use when you need to analyze index metrics such as record counts, query volumes, processing times, or capacity usage. Supports both hourly and daily aggregation granularity.',
		pathParams: ['indexName'],
		queryParams: ['endDate', 'startDate', 'statistic', 'granularity'],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUsers',
		group: 'personalization',
		name: 'getUsers',
		method: 'GET',
		path: '/2/users',
		hostType: 'personalization',
		description:
			'Tool to retrieve a list of user profiles from Algolia advanced personalization. Use when you need to fetch user affinities, filter by date ranges, or paginate through user data.',
		pathParams: [],
		queryParams: [
			'limit',
			'endDate',
			'indices',
			'affinity',
			'startDate',
			'nextPageToken',
			'previousPageToken',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'getUsersCount',
		group: 'analytics',
		name: 'getUsersCount',
		method: 'GET',
		path: '/2/users/count',
		hostType: 'analytics',
		description:
			'Tool to retrieve the number of unique users within a time range, including daily breakdown. Use when you need to analyze user engagement metrics for a specific index over a date range.',
		pathParams: [],
		queryParams: ['tags', 'index', 'endDate', 'startDate'],
		riskLevel: 'read' as const,
	},
	{
		key: 'initInsights',
		group: 'insights',
		name: 'initInsights',
		method: 'POST',
		path: '/1/events',
		hostType: 'insights',
		description:
			'Tool to initialize the Algolia Insights API client. Use before sending any Insights events.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'listAbTests',
		group: 'abTests',
		name: 'listAbTests',
		method: 'GET',
		path: '/2/abtests',
		hostType: 'analytics',
		description:
			'Tool to list all A/B tests configured for this application. Use when you need to view existing A/B tests, check their status, or retrieve test IDs for further operations.',
		pathParams: [],
		queryParams: ['limit', 'offset', 'indexPrefix', 'indexSuffix'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listApiKeys',
		group: 'apiKeys',
		name: 'listApiKeys',
		method: 'GET',
		path: '/1/keys',
		hostType: 'search',
		description:
			'Tool to list all API keys associated with your Algolia application, including their permissions and restrictions. Use when you need to audit API key usage, check permissions, or manage access control. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listAuthentications',
		group: 'authentications',
		name: 'listAuthentications',
		method: 'GET',
		path: '/1/authentications',
		hostType: 'ingestion',
		description:
			'Tool to list authentication resources from Algolia. Use when you need to retrieve available authentication configurations for sources or destinations.',
		pathParams: [],
		queryParams: ['page', 'sort', 'type', 'order', 'platform', 'itemsPerPage'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listDestinations',
		group: 'destinations',
		name: 'listDestinations',
		method: 'GET',
		path: '/1/destinations',
		hostType: 'ingestion',
		description:
			'Tool to list destinations in Algolia. Use when you need to retrieve all destinations or filter them by type, authentication ID, or transformation ID.',
		pathParams: [],
		queryParams: [
			'page',
			'sort',
			'type',
			'order',
			'itemsPerPage',
			'authenticationID',
			'transformationID',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listIndices',
		group: 'indices',
		name: 'listIndices',
		method: 'GET',
		path: '/1/indexes',
		hostType: 'search',
		description:
			'Tool to list all indices and their metadata. Use when you need to retrieve index names, sizes, and state before performing operations that depend on index properties. #### Output | Parameter | Type | Required | Description | |-----------|------|----------|-------------| | `data` | string | Yes | Data from the action execution | | `error` | string | No | Error if any occurred during the execution of the action | | `successful` | boolean | Yes | Whether or not the action execution was successful or not |',
		pathParams: [],
		queryParams: [],
		riskLevel: 'read' as const,
	},
	{
		key: 'listIngestionTasks',
		group: 'tasks',
		name: 'listIngestionTasks',
		method: 'GET',
		path: '/2/tasks',
		hostType: 'ingestion',
		description:
			'Tool to retrieve a list of ingestion tasks from Algolia. Use when you need to fetch configured tasks for ingestion pipelines. Supports filtering by various criteria such as source, destination, trigger type, action, and enabled status, with pagination and sorting.',
		pathParams: [],
		queryParams: [
			'page',
			'sort',
			'order',
			'action',
			'enabled',
			'sourceID',
			'sourceType',
			'triggerType',
			'itemsPerPage',
			'destinationID',
			'withEmailNotifications',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listQsConfigs',
		group: 'querySuggestions',
		name: 'listQsConfigs',
		method: 'GET',
		path: '/1/configs',
		hostType: 'querySuggestions',
		description:
			'Tool to retrieve all Query Suggestions configurations for an Algolia application. Use when you need to view or audit existing Query Suggestions setups.',
		pathParams: [],
		queryParams: ['region'],
		riskLevel: 'read' as const,
	},
	{
		key: 'listRuns',
		group: 'runs',
		name: 'listRuns',
		method: 'GET',
		path: '/1/runs',
		hostType: 'ingestion',
		description:
			'Tool to list task runs. Use when you need to retrieve and monitor task execution status, filter by time range, or paginate through run history.',
		pathParams: [],
		queryParams: [
			'page',
			'sort',
			'type',
			'order',
			'status',
			'taskID',
			'endDate',
			'startDate',
			'itemsPerPage',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listSources',
		group: 'sources',
		name: 'listSources',
		method: 'GET',
		path: '/1/sources',
		hostType: 'ingestion',
		description:
			'Tool to list sources from the Algolia Ingestion API. Use when you need to retrieve available data sources for ingestion pipelines. Supports filtering by type and authentication ID, with pagination and sorting options.',
		pathParams: [],
		queryParams: [
			'page',
			'sort',
			'type',
			'order',
			'region',
			'itemsPerPage',
			'authenticationID',
		],
		riskLevel: 'read' as const,
	},
	{
		key: 'listTransformations',
		group: 'transformations',
		name: 'listTransformations',
		method: 'GET',
		path: '/1/transformations',
		hostType: 'ingestion',
		description:
			'Tool to list all transformations in Algolia Ingestion API. Use when you need to retrieve transformation configurations, filter by type, or paginate through transformation lists.',
		pathParams: [],
		queryParams: ['page', 'sort', 'type', 'order', 'itemsPerPage'],
		riskLevel: 'read' as const,
	},
	{
		key: 'partialUpdateObjects',
		group: 'indices',
		name: 'partialUpdateObjects',
		method: 'POST',
		path: '/1/indexes/{indexName}/batch',
		hostType: 'search',
		description:
			'Tool to partially update multiple records in the specified index. Use when you need to change only selected fields of many objects without replacing entire records. Use after confirming objectIDs and desired updates.',
		pathParams: ['indexName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'pushTask',
		group: 'tasks',
		name: 'pushTask',
		method: 'POST',
		path: '/2/tasks/{taskID}/push',
		hostType: 'ingestion',
		description:
			"Tool to push records to an Algolia task by task ID. Use when you need to send data to a configured ingestion task. Note: tasks with source type 'json' cannot use this endpoint.",
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'replaceAllRules',
		group: 'rules',
		name: 'replaceAllRules',
		method: 'POST',
		path: '/1/indexes/{indexName}/rules/batch',
		hostType: 'search',
		description:
			'Tool to push a new set of rules, erasing previous ones. Use when you need zero-downtime atomic replacement of all rules in an index.',
		pathParams: ['indexName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'replaceTask',
		group: 'tasks',
		name: 'replaceTask',
		method: 'PUT',
		path: '/2/tasks/{taskID}',
		hostType: 'ingestion',
		description:
			'Tool to fully replace a task in Algolia Ingestion API. Use when you need to completely update a task with new configuration, replacing all existing settings.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'restoreApiKey',
		group: 'apiKeys',
		name: 'restoreApiKey',
		method: 'POST',
		path: '/1/keys/{key}/restore',
		hostType: 'search',
		description:
			'Tool to restore a deleted API key within 72 hours of deletion. Use when you need to recover an accidentally deleted API key.',
		pathParams: ['key'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'runTaskV1',
		group: 'tasks',
		name: 'runTaskV1',
		method: 'POST',
		path: '/1/tasks/{taskID}/run',
		hostType: 'ingestion',
		description:
			'Tool to run a task V1 from Algolia Ingestion API. Use when you need to manually trigger a task execution. Note: This API is deprecated but still functional.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'saveRule',
		group: 'rules',
		name: 'saveRule',
		method: 'PUT',
		path: '/1/indexes/{indexName}/rules/{objectID}',
		hostType: 'search',
		description:
			'Tool to create or replace a rule in an index. Use when you need to add merchandising rules, query modifications, or conditional search behavior.',
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'saveSynonym',
		group: 'synonyms',
		name: 'saveSynonym',
		method: 'PUT',
		path: '/1/indexes/{indexName}/synonyms/{objectID}',
		hostType: 'search',
		description:
			'Tool to add or update a synonym in the specified index. Use when you need programmatic upsert of search synonyms after index creation.',
		pathParams: ['indexName', 'objectID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'saveSynonyms',
		group: 'synonyms',
		name: 'saveSynonyms',
		method: 'POST',
		path: '/1/indexes/{indexName}/synonyms/batch',
		hostType: 'search',
		description:
			"Tool to batch create or replace synonyms in an Algolia index. If a synonym with the objectID doesn't exist, Algolia adds a new one. Use when you need to add or update multiple synonyms at once.",
		pathParams: ['indexName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchAuthentications',
		group: 'authentications',
		name: 'searchAuthentications',
		method: 'POST',
		path: '/1/authentications/search',
		hostType: 'ingestion',
		description:
			'Tool to search for authentication resources by IDs in Algolia. Use when you need to retrieve multiple specific authentication configurations by their IDs.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchDestinations',
		group: 'destinations',
		name: 'searchDestinations',
		method: 'POST',
		path: '/1/destinations/search',
		hostType: 'ingestion',
		description:
			'Tool to search for specific destinations by their IDs. Use when you need to retrieve multiple destinations at once by providing their unique identifiers.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchDictionaryEntries',
		group: 'dictionaries',
		name: 'searchDictionaryEntries',
		method: 'POST',
		path: '/1/dictionaries/{dictionaryName}/search',
		hostType: 'search',
		description:
			'Tool to search dictionary entries in Algolia dictionaries. Use when you need to find stopwords, plurals, or compound words in specific dictionaries.',
		pathParams: ['dictionary_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchFacetValues',
		group: 'search',
		name: 'searchFacetValues',
		method: 'POST',
		path: '/1/indexes/{indexName}/facets/{facetName}/query',
		hostType: 'search',
		description:
			'Tool to search for values of a specified facet attribute. Use when you need to find specific facet values that match a query string. Facet values are sorted by decreasing count by default.',
		pathParams: ['index_name', 'facet_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchIndex',
		group: 'search',
		name: 'searchIndex',
		method: 'POST',
		path: '/1/indexes/{indexName}/query',
		hostType: 'search',
		description:
			"Tool to perform a search on a specified Algolia index. Use after confirming the index name. Example: SearchIndex(index_name='contacts', query='apple', search_params={'hitsPerPage':10})",
		pathParams: ['index_name'],
		queryParams: [],
		// Algolia's search endpoint uses POST because the query goes in the
		// body (long queries, structured params), but the call is read-only.
		riskLevel: 'read' as const,
	},
	{
		key: 'searchMultipleIndices',
		group: 'search',
		name: 'searchMultipleIndices',
		method: 'POST',
		path: '/1/indexes/*/queries',
		hostType: 'search',
		description:
			'Tool to perform searches across multiple indices in a single call. Use when you need to batch multiple index queries into one API request.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchRecommendRules',
		group: 'rules',
		name: 'searchRecommendRules',
		method: 'POST',
		path: '/1/indexes/{indexName}/{model}/recommend/rules/search',
		hostType: 'search',
		description:
			'Tool to search for Recommend rules in the specified index and model. Use when you need to retrieve rules matching a query, or use an empty query to list all rules for this recommendation scenario.',
		pathParams: ['index_name', 'model'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchSources',
		group: 'sources',
		name: 'searchSources',
		method: 'POST',
		path: '/1/sources/search',
		hostType: 'ingestion',
		description:
			'Tool to search for sources by IDs in Algolia Ingestion API. Use when you need to retrieve multiple specific data sources by their IDs.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchSynonyms',
		group: 'synonyms',
		name: 'searchSynonyms',
		method: 'POST',
		path: '/1/indexes/{indexName}/synonyms/search',
		hostType: 'search',
		description:
			'Tool to search for synonyms in the specified index. Use when you need to retrieve synonyms matching a query or filter by type.',
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchTasksV1',
		group: 'tasks',
		name: 'searchTasksV1',
		method: 'POST',
		path: '/1/tasks/search',
		hostType: 'ingestion',
		description:
			'Tool to search for tasks V1 from Algolia Ingestion API. Use when you need to retrieve details about multiple specific tasks by their IDs. Note: This API is deprecated.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'searchTransformations',
		group: 'transformations',
		name: 'searchTransformations',
		method: 'POST',
		path: '/1/transformations/search',
		hostType: 'ingestion',
		description:
			'Tool to search for transformations by IDs in Algolia Ingestion API. Use when you need to retrieve multiple specific transformation configurations by their IDs.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'setDictionarySettings',
		group: 'dictionaries',
		name: 'setDictionarySettings',
		method: 'PUT',
		path: '/1/dictionaries/*/settings',
		hostType: 'search',
		description:
			'Tool to update dictionary settings for Algolia. Use when you need to enable or disable built-in stop words, plurals, or compounds for specific languages.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'setPersonalizationStrategy',
		group: 'personalization',
		name: 'setPersonalizationStrategy',
		method: 'PUT',
		path: '/1/strategies/personalization',
		hostType: 'search',
		description:
			'Tool to define personalization strategy that controls how user behavior affects search results. Use when you need to configure which events and facets influence personalized search rankings.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'setSettings',
		group: 'indices',
		name: 'setSettings',
		method: 'PUT',
		path: '/1/indexes/{indexName}/settings',
		hostType: 'search',
		description:
			"Tool to update an Algolia index's settings. Use when you need to configure index behavior before indexing records. Example: set searchableAttributes and customRanking for products index.",
		pathParams: ['index_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'stopAbTest',
		group: 'abTests',
		name: 'stopAbTest',
		method: 'POST',
		path: '/2/abtests/{id}/stop',
		hostType: 'analytics',
		description:
			'Tool to stop an A/B test by its unique identifier. Use when you need to halt an active A/B test. Note that stopped A/B tests cannot be restarted.',
		pathParams: ['id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'tryTransformation',
		group: 'transformations',
		name: 'tryTransformation',
		method: 'POST',
		path: '/1/transformations/try',
		hostType: 'ingestion',
		description:
			'Tool to try a transformation before creating it in Algolia. Use when you need to test transformation code or no-code configurations against sample data to verify they work correctly before deployment.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'tryTransformationBeforeUpdate',
		group: 'transformations',
		name: 'tryTransformationBeforeUpdate',
		method: 'POST',
		path: '/1/transformations/{transformationID}/try',
		hostType: 'ingestion',
		description:
			'Tool to test a transformation before updating it in Algolia Ingestion API. Use when you need to validate transformation code or configuration against sample data before applying it to production.',
		pathParams: ['transformation_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateApiKey',
		group: 'apiKeys',
		name: 'updateApiKey',
		method: 'PUT',
		path: '/1/keys/{key}',
		hostType: 'search',
		description:
			'Tool to update the permissions and settings of an existing API key. Use when you need to modify ACL permissions, index restrictions, rate limits, or other settings of an existing API key.',
		pathParams: ['key'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateAuthentication',
		group: 'authentications',
		name: 'updateAuthentication',
		method: 'PATCH',
		path: '/1/authentications/{authenticationID}',
		hostType: 'ingestion',
		description:
			'Tool to update an authentication resource in Algolia. Use when you need to modify the name or credentials of an existing authentication configuration.',
		pathParams: ['authenticationID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateConfig',
		group: 'querySuggestions',
		name: 'updateConfig',
		method: 'PUT',
		path: '/1/configs/{indexName}',
		hostType: 'querySuggestions',
		description:
			'Tool to update an existing Query Suggestions configuration. Use when you need to modify settings for query suggestions on an existing index.',
		pathParams: ['indexName'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDestination',
		group: 'destinations',
		name: 'updateDestination',
		method: 'PATCH',
		path: '/1/destinations/{destinationID}',
		hostType: 'ingestion',
		description:
			"Tool to update a destination in Algolia Ingestion API. Use when you need to modify an existing destination's configuration, name, type, or associated transformations.",
		pathParams: ['destinationID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateDictionaryEntries',
		group: 'dictionaries',
		name: 'updateDictionaryEntries',
		method: 'POST',
		path: '/1/dictionaries/{dictionaryName}/batch',
		hostType: 'search',
		description:
			'Tool to add or delete dictionary entries in Algolia dictionaries. Use when you need to batch modify stopwords, plurals, or compound word entries.',
		pathParams: ['dictionary_name'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateRecordPartially',
		group: 'indices',
		name: 'updateRecordPartially',
		method: 'POST',
		path: '/1/indexes/{indexName}/{objectID}/partial',
		hostType: 'search',
		description:
			"Tool to add or update attributes in a single record. Use when you need to modify specific fields without replacing the entire record. Creates a new record if the objectID doesn't exist (when create_if_not_exists is true).",
		pathParams: ['index_name', 'object_id'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateSource',
		group: 'sources',
		name: 'updateSource',
		method: 'PATCH',
		path: '/1/sources/{sourceID}',
		hostType: 'ingestion',
		description:
			'Tool to update a source in the Algolia Ingestion API. Use when you need to modify the name, authentication, or input configuration of an existing data source.',
		pathParams: ['sourceID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTask',
		group: 'tasks',
		name: 'updateTask',
		method: 'PATCH',
		path: '/2/tasks/{taskID}',
		hostType: 'ingestion',
		description:
			'Tool to partially update a task in Algolia Ingestion API. Use when you need to modify task configuration such as schedule, failure threshold, destination, or notification settings.',
		pathParams: ['taskID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'updateTransformation',
		group: 'transformations',
		name: 'updateTransformation',
		method: 'PATCH',
		path: '/1/transformations/{transformationID}',
		hostType: 'ingestion',
		description:
			'Tool to update an existing transformation in Algolia Ingestion API. Use when you need to modify transformation settings, code, or configuration for data processing during ingestion.',
		pathParams: ['transformationID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'validateSource',
		group: 'sources',
		name: 'validateSource',
		method: 'POST',
		path: '/1/sources/validate',
		hostType: 'ingestion',
		description:
			'Tool to validate a source payload before creating it in Algolia. Use when you need to verify that a source configuration is valid before actually creating the source.',
		pathParams: [],
		queryParams: [],
		riskLevel: 'write' as const,
	},
	{
		key: 'validateSourceBeforeUpdate',
		group: 'sources',
		name: 'validateSourceBeforeUpdate',
		method: 'POST',
		path: '/1/sources/{sourceID}/validate',
		hostType: 'ingestion',
		description:
			'Tool to validate a source update payload in the Algolia Ingestion API. Use when you need to verify that an update to a source configuration is valid before actually updating it.',
		pathParams: ['sourceID'],
		queryParams: [],
		riskLevel: 'write' as const,
	},
] as const;

export type AlgoliaRoutes = typeof algoliaRoutes;
