export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

export type OpSpec = {
	key: string;
	nested: string;
	risk: 'read' | 'write';
	description: string;
	method: HttpMethod;
	path: string;
	pathKeys?: string[];
	queryKeys?: string[];
	body?: true | 'omit';
	responseHeader?: string;
	mapHeader?: 'x_message_id';
	wrapArray?: string;
	upsertList?: boolean;
	inKind: string;
	outKind: string;
};

export const SENDGRID_OPS: OpSpec[] = [
	{
		key: 'mailSend',
		nested: 'mail.send',
		risk: 'write',
		description: 'Send an email via SendGrid Mail Send API v3',
		method: 'POST',
		path: 'mail/send',
		body: true,
		responseHeader: 'X-Message-Id',
		mapHeader: 'x_message_id',
		inKind: 'mailSend',
		outKind: 'mailSend',
	},
	{
		key: 'mailCreateBatchId',
		nested: 'mail.createBatchId',
		risk: 'write',
		description: 'Create a batch ID for scheduled mail',
		method: 'POST',
		path: 'mail/batch',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'mailValidateBatchId',
		nested: 'mail.validateBatchId',
		risk: 'read',
		description: 'Validate a mail batch ID',
		method: 'GET',
		path: 'mail/batch/{batch_id}',
		pathKeys: ['batch_id'],
		inKind: 'batchId',
		outKind: 'obj',
	},
	{
		key: 'mailCancelScheduledSend',
		nested: 'mail.cancelScheduledSend',
		risk: 'write',
		description: 'Cancel or pause a scheduled send',
		method: 'POST',
		path: 'user/scheduled_sends',
		body: true,
		inKind: 'scheduledSend',
		outKind: 'obj',
	},
	{
		key: 'mailListScheduledSends',
		nested: 'mail.listScheduledSends',
		risk: 'read',
		description: 'Retrieve all scheduled sends',
		method: 'GET',
		path: 'user/scheduled_sends',
		inKind: 'empty',
		outKind: 'arr',
	},
	{
		key: 'mailGetScheduledSend',
		nested: 'mail.getScheduledSend',
		risk: 'read',
		description: 'Retrieve a scheduled send by batch ID',
		method: 'GET',
		path: 'user/scheduled_sends/{batch_id}',
		pathKeys: ['batch_id'],
		inKind: 'batchId',
		outKind: 'arr',
	},
	{
		key: 'mailUpdateScheduledSend',
		nested: 'mail.updateScheduledSend',
		risk: 'write',
		description: 'Update a scheduled send status',
		method: 'PATCH',
		path: 'user/scheduled_sends/{batch_id}',
		pathKeys: ['batch_id'],
		body: 'omit',
		inKind: 'scheduledSendUpdate',
		outKind: 'empty',
	},
	{
		key: 'mailDeleteScheduledSend',
		nested: 'mail.deleteScheduledSend',
		risk: 'write',
		description: 'Delete a cancellation/pause for a scheduled send',
		method: 'DELETE',
		path: 'user/scheduled_sends/{batch_id}',
		pathKeys: ['batch_id'],
		inKind: 'batchId',
		outKind: 'empty',
	},
	{
		key: 'contactsAddOrUpdate',
		nested: 'contacts.addOrUpdate',
		risk: 'write',
		description: 'Add or update contacts in SendGrid Marketing',
		method: 'PUT',
		path: 'marketing/contacts',
		body: true,
		inKind: 'contactsAddOrUpdate',
		outKind: 'job',
	},
	{
		key: 'contactsGet',
		nested: 'contacts.get',
		risk: 'read',
		description: 'Get a marketing contact by ID',
		method: 'GET',
		path: 'marketing/contacts/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'obj',
	},
	{
		key: 'contactsSearch',
		nested: 'contacts.search',
		risk: 'read',
		description: 'Search marketing contacts with SGQL',
		method: 'POST',
		path: 'marketing/contacts/search',
		body: true,
		inKind: 'contactSearch',
		outKind: 'obj',
	},
	{
		key: 'contactsSearchEmails',
		nested: 'contacts.searchEmails',
		risk: 'read',
		description: 'Search marketing contacts by email',
		method: 'POST',
		path: 'marketing/contacts/search/emails',
		body: true,
		inKind: 'contactSearchEmails',
		outKind: 'obj',
	},
	{
		key: 'contactsRemove',
		nested: 'contacts.remove',
		risk: 'write',
		description: 'Delete marketing contacts by ID',
		method: 'DELETE',
		path: 'marketing/contacts',
		queryKeys: ['ids'],
		inKind: 'idsQuery',
		outKind: 'job',
	},
	{
		key: 'contactsGetCount',
		nested: 'contacts.getCount',
		risk: 'read',
		description: 'Get marketing contact count',
		method: 'GET',
		path: 'marketing/contacts/count',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'contactsGetSample',
		nested: 'contacts.getSample',
		risk: 'read',
		description: 'Get a sample of marketing contacts',
		method: 'GET',
		path: 'marketing/contacts',
		queryKeys: ['page_size', 'page_token'],
		inKind: 'page',
		outKind: 'obj',
	},
	{
		key: 'contactsImport',
		nested: 'contacts.import',
		risk: 'write',
		description: 'Create a marketing contacts import job',
		method: 'PUT',
		path: 'marketing/contacts/imports',
		body: true,
		inKind: 'contactImport',
		outKind: 'obj',
	},
	{
		key: 'contactsImportStatus',
		nested: 'contacts.importStatus',
		risk: 'read',
		description: 'Get a marketing contacts import job',
		method: 'GET',
		path: 'marketing/contacts/imports/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'obj',
	},
	{
		key: 'contactsExport',
		nested: 'contacts.export',
		risk: 'write',
		description: 'Create a marketing contacts export job',
		method: 'POST',
		path: 'marketing/contacts/exports',
		body: true,
		inKind: 'contactExport',
		outKind: 'obj',
	},
	{
		key: 'contactsExportStatus',
		nested: 'contacts.exportStatus',
		risk: 'read',
		description: 'Get a marketing contacts export job',
		method: 'GET',
		path: 'marketing/contacts/exports/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'obj',
	},
	{
		key: 'contactsListExports',
		nested: 'contacts.listExports',
		risk: 'read',
		description: 'List marketing contacts export jobs',
		method: 'GET',
		path: 'marketing/contacts/exports',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'listsGetAll',
		nested: 'lists.getAll',
		risk: 'read',
		description: 'Retrieve all marketing contact lists',
		method: 'GET',
		path: 'marketing/lists',
		queryKeys: ['page_size', 'page_token'],
		inKind: 'page',
		outKind: 'listsGetAll',
	},
	{
		key: 'listsCreate',
		nested: 'lists.create',
		risk: 'write',
		description: 'Create a new marketing contact list',
		method: 'POST',
		path: 'marketing/lists',
		body: true,
		upsertList: true,
		inKind: 'listsCreate',
		outKind: 'list',
	},
	{
		key: 'listsGet',
		nested: 'lists.get',
		risk: 'read',
		description: 'Get a marketing list by ID',
		method: 'GET',
		path: 'marketing/lists/{id}',
		pathKeys: ['id'],
		queryKeys: ['contact_sample'],
		inKind: 'idSample',
		outKind: 'obj',
	},
	{
		key: 'listsUpdate',
		nested: 'lists.update',
		risk: 'write',
		description: 'Update a marketing list',
		method: 'PATCH',
		path: 'marketing/lists/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'idName',
		outKind: 'list',
	},
	{
		key: 'listsRemove',
		nested: 'lists.remove',
		risk: 'write',
		description: 'Delete a marketing list',
		method: 'DELETE',
		path: 'marketing/lists/{id}',
		pathKeys: ['id'],
		queryKeys: ['delete_contacts'],
		inKind: 'idDeleteContacts',
		outKind: 'empty',
	},
	{
		key: 'listsGetContactCount',
		nested: 'lists.getContactCount',
		risk: 'read',
		description: 'Get contact count for a marketing list',
		method: 'GET',
		path: 'marketing/lists/{id}/contacts/count',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'obj',
	},
	{
		key: 'listsRemoveContacts',
		nested: 'lists.removeContacts',
		risk: 'write',
		description: 'Remove contacts from a marketing list',
		method: 'DELETE',
		path: 'marketing/lists/{id}/contacts',
		pathKeys: ['id'],
		queryKeys: ['contact_ids'],
		inKind: 'idContactIds',
		outKind: 'job',
	},
	{
		key: 'segmentsCreate',
		nested: 'segments.create',
		risk: 'write',
		description: 'Create a Marketing Campaigns segment 2.0',
		method: 'POST',
		path: 'marketing/segments/2.0',
		body: true,
		inKind: 'segment',
		outKind: 'obj',
	},
	{
		key: 'segmentsGetAll',
		nested: 'segments.getAll',
		risk: 'read',
		description: 'Get all Marketing Campaigns segments 2.0',
		method: 'GET',
		path: 'marketing/segments/2.0',
		queryKeys: ['parent_list_ids', 'no_parent_list_id'],
		inKind: 'segmentsList',
		outKind: 'obj',
	},
	{
		key: 'segmentsGet',
		nested: 'segments.get',
		risk: 'read',
		description: 'Get a Marketing Campaigns segment 2.0',
		method: 'GET',
		path: 'marketing/segments/2.0/{id}',
		pathKeys: ['id'],
		queryKeys: ['contacts_sample'],
		inKind: 'idContactsSample',
		outKind: 'obj',
	},
	{
		key: 'segmentsUpdate',
		nested: 'segments.update',
		risk: 'write',
		description: 'Update a Marketing Campaigns segment 2.0',
		method: 'PATCH',
		path: 'marketing/segments/2.0/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'segmentUpdate',
		outKind: 'obj',
	},
	{
		key: 'segmentsRemove',
		nested: 'segments.remove',
		risk: 'write',
		description: 'Delete a Marketing Campaigns segment 2.0',
		method: 'DELETE',
		path: 'marketing/segments/2.0/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'empty',
	},
	{
		key: 'segmentsRefresh',
		nested: 'segments.refresh',
		risk: 'write',
		description: 'Manually refresh a Marketing Campaigns segment 2.0',
		method: 'POST',
		path: 'marketing/segments/2.0/refresh/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'segmentRefresh',
		outKind: 'obj',
	},
	{
		key: 'fieldsGetAll',
		nested: 'fields.getAll',
		risk: 'read',
		description: 'Get all marketing field definitions',
		method: 'GET',
		path: 'marketing/field_definitions',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'fieldsCreate',
		nested: 'fields.create',
		risk: 'write',
		description: 'Create a custom field definition',
		method: 'POST',
		path: 'marketing/field_definitions',
		body: true,
		inKind: 'fieldCreate',
		outKind: 'obj',
	},
	{
		key: 'fieldsUpdate',
		nested: 'fields.update',
		risk: 'write',
		description: 'Update a custom field definition',
		method: 'PATCH',
		path: 'marketing/field_definitions/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'idName',
		outKind: 'obj',
	},
	{
		key: 'fieldsRemove',
		nested: 'fields.remove',
		risk: 'write',
		description: 'Delete a custom field definition',
		method: 'DELETE',
		path: 'marketing/field_definitions/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'empty',
	},
	{
		key: 'sendersGetAll',
		nested: 'senders.getAll',
		risk: 'read',
		description: 'Retrieve verified senders',
		method: 'GET',
		path: 'verified_senders',
		queryKeys: ['limit', 'lastSeenID', 'id'],
		inKind: 'sendersGetAll',
		outKind: 'sendersGetAll',
	},
	{
		key: 'sendersCreate',
		nested: 'senders.create',
		risk: 'write',
		description: 'Create a verified sender',
		method: 'POST',
		path: 'verified_senders',
		body: true,
		inKind: 'verifiedSender',
		outKind: 'obj',
	},
	{
		key: 'sendersUpdate',
		nested: 'senders.update',
		risk: 'write',
		description: 'Update a verified sender',
		method: 'PATCH',
		path: 'verified_senders/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'verifiedSenderUpdate',
		outKind: 'obj',
	},
	{
		key: 'sendersRemove',
		nested: 'senders.remove',
		risk: 'write',
		description: 'Delete a verified sender',
		method: 'DELETE',
		path: 'verified_senders/{id}',
		pathKeys: ['id'],
		inKind: 'idNum',
		outKind: 'empty',
	},
	{
		key: 'sendersResend',
		nested: 'senders.resend',
		risk: 'write',
		description: 'Resend verified sender verification',
		method: 'POST',
		path: 'verified_senders/resend/{id}',
		pathKeys: ['id'],
		inKind: 'idNum',
		outKind: 'empty',
	},
	{
		key: 'sendersListIdentities',
		nested: 'senders.listIdentities',
		risk: 'read',
		description: 'Get Marketing Campaigns sender identities',
		method: 'GET',
		path: 'senders',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'sendersCreateIdentity',
		nested: 'senders.createIdentity',
		risk: 'write',
		description: 'Create a Marketing Campaigns sender identity',
		method: 'POST',
		path: 'senders',
		body: true,
		inKind: 'senderIdentity',
		outKind: 'obj',
	},
	{
		key: 'sendersGetIdentity',
		nested: 'senders.getIdentity',
		risk: 'read',
		description: 'Get a Marketing Campaigns sender identity',
		method: 'GET',
		path: 'senders/{id}',
		pathKeys: ['id'],
		inKind: 'idNum',
		outKind: 'obj',
	},
	{
		key: 'templatesCreate',
		nested: 'templates.create',
		risk: 'write',
		description: 'Create a transactional template',
		method: 'POST',
		path: 'templates',
		body: true,
		inKind: 'templateCreate',
		outKind: 'obj',
	},
	{
		key: 'templatesGetAll',
		nested: 'templates.getAll',
		risk: 'read',
		description: 'Get all transactional templates',
		method: 'GET',
		path: 'templates',
		queryKeys: ['generations', 'page_size'],
		inKind: 'templatesList',
		outKind: 'obj',
	},
	{
		key: 'templatesGet',
		nested: 'templates.get',
		risk: 'read',
		description: 'Get a transactional template',
		method: 'GET',
		path: 'templates/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'obj',
	},
	{
		key: 'templatesUpdate',
		nested: 'templates.update',
		risk: 'write',
		description: 'Update a transactional template',
		method: 'PATCH',
		path: 'templates/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'idName',
		outKind: 'obj',
	},
	{
		key: 'templatesRemove',
		nested: 'templates.remove',
		risk: 'write',
		description: 'Delete a transactional template',
		method: 'DELETE',
		path: 'templates/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'empty',
	},
	{
		key: 'templatesCreateVersion',
		nested: 'templates.createVersion',
		risk: 'write',
		description: 'Create a transactional template version',
		method: 'POST',
		path: 'templates/{id}/versions',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'templateVersion',
		outKind: 'obj',
	},
	{
		key: 'templatesGetVersion',
		nested: 'templates.getVersion',
		risk: 'read',
		description: 'Get a transactional template version',
		method: 'GET',
		path: 'templates/{id}/versions/{version_id}',
		pathKeys: ['id', 'version_id'],
		inKind: 'templateVersionId',
		outKind: 'obj',
	},
	{
		key: 'templatesUpdateVersion',
		nested: 'templates.updateVersion',
		risk: 'write',
		description: 'Update a transactional template version',
		method: 'PATCH',
		path: 'templates/{id}/versions/{version_id}',
		pathKeys: ['id', 'version_id'],
		body: 'omit',
		inKind: 'templateVersionUpdate',
		outKind: 'obj',
	},
	{
		key: 'templatesRemoveVersion',
		nested: 'templates.removeVersion',
		risk: 'write',
		description: 'Delete a transactional template version',
		method: 'DELETE',
		path: 'templates/{id}/versions/{version_id}',
		pathKeys: ['id', 'version_id'],
		inKind: 'templateVersionId',
		outKind: 'empty',
	},
	{
		key: 'templatesActivateVersion',
		nested: 'templates.activateVersion',
		risk: 'write',
		description: 'Activate a transactional template version',
		method: 'POST',
		path: 'templates/{id}/versions/{version_id}/activate',
		pathKeys: ['id', 'version_id'],
		inKind: 'templateVersionId',
		outKind: 'obj',
	},
	{
		key: 'suppressionsGetBounces',
		nested: 'suppressions.getBounces',
		risk: 'read',
		description: 'Retrieve email bounce suppressions',
		method: 'GET',
		path: 'suppression/bounces',
		queryKeys: ['start_time', 'end_time', 'limit', 'offset'],
		wrapArray: 'bounces',
		inKind: 'suppressionList',
		outKind: 'bounces',
	},
	{
		key: 'suppressionsGetBounce',
		nested: 'suppressions.getBounce',
		risk: 'read',
		description: 'Retrieve a bounce by email',
		method: 'GET',
		path: 'suppression/bounces/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'arr',
	},
	{
		key: 'suppressionsDeleteBounce',
		nested: 'suppressions.deleteBounce',
		risk: 'write',
		description: 'Delete a bounce by email',
		method: 'DELETE',
		path: 'suppression/bounces/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'empty',
	},
	{
		key: 'suppressionsDeleteBounces',
		nested: 'suppressions.deleteBounces',
		risk: 'write',
		description: 'Delete bounce suppressions',
		method: 'DELETE',
		path: 'suppression/bounces',
		body: true,
		inKind: 'deleteSuppressions',
		outKind: 'empty',
	},
	{
		key: 'suppressionsGetBlocks',
		nested: 'suppressions.getBlocks',
		risk: 'read',
		description: 'Retrieve blocked emails',
		method: 'GET',
		path: 'suppression/blocks',
		queryKeys: ['start_time', 'end_time', 'limit', 'offset'],
		wrapArray: 'results',
		inKind: 'suppressionList',
		outKind: 'results',
	},
	{
		key: 'suppressionsGetBlock',
		nested: 'suppressions.getBlock',
		risk: 'read',
		description: 'Retrieve a block by email',
		method: 'GET',
		path: 'suppression/blocks/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'arr',
	},
	{
		key: 'suppressionsDeleteBlock',
		nested: 'suppressions.deleteBlock',
		risk: 'write',
		description: 'Delete a block by email',
		method: 'DELETE',
		path: 'suppression/blocks/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'empty',
	},
	{
		key: 'suppressionsDeleteBlocks',
		nested: 'suppressions.deleteBlocks',
		risk: 'write',
		description: 'Delete blocked emails',
		method: 'DELETE',
		path: 'suppression/blocks',
		body: true,
		inKind: 'deleteSuppressions',
		outKind: 'empty',
	},
	{
		key: 'suppressionsGetSpamReports',
		nested: 'suppressions.getSpamReports',
		risk: 'read',
		description: 'Retrieve spam reports',
		method: 'GET',
		path: 'suppression/spam_reports',
		queryKeys: ['start_time', 'end_time', 'limit', 'offset'],
		wrapArray: 'results',
		inKind: 'suppressionList',
		outKind: 'results',
	},
	{
		key: 'suppressionsGetSpamReport',
		nested: 'suppressions.getSpamReport',
		risk: 'read',
		description: 'Retrieve a spam report by email',
		method: 'GET',
		path: 'suppression/spam_reports/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'arr',
	},
	{
		key: 'suppressionsDeleteSpamReport',
		nested: 'suppressions.deleteSpamReport',
		risk: 'write',
		description: 'Delete a spam report by email',
		method: 'DELETE',
		path: 'suppression/spam_reports/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'empty',
	},
	{
		key: 'suppressionsDeleteSpamReports',
		nested: 'suppressions.deleteSpamReports',
		risk: 'write',
		description: 'Delete spam reports',
		method: 'DELETE',
		path: 'suppression/spam_reports',
		body: true,
		inKind: 'deleteSuppressions',
		outKind: 'empty',
	},
	{
		key: 'suppressionsGetInvalidEmails',
		nested: 'suppressions.getInvalidEmails',
		risk: 'read',
		description: 'Retrieve invalid emails',
		method: 'GET',
		path: 'suppression/invalid_emails',
		queryKeys: ['start_time', 'end_time', 'limit', 'offset'],
		wrapArray: 'results',
		inKind: 'suppressionList',
		outKind: 'results',
	},
	{
		key: 'suppressionsGetInvalidEmail',
		nested: 'suppressions.getInvalidEmail',
		risk: 'read',
		description: 'Retrieve an invalid email',
		method: 'GET',
		path: 'suppression/invalid_emails/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'arr',
	},
	{
		key: 'suppressionsDeleteInvalidEmail',
		nested: 'suppressions.deleteInvalidEmail',
		risk: 'write',
		description: 'Delete an invalid email',
		method: 'DELETE',
		path: 'suppression/invalid_emails/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'empty',
	},
	{
		key: 'suppressionsDeleteInvalidEmails',
		nested: 'suppressions.deleteInvalidEmails',
		risk: 'write',
		description: 'Delete invalid emails',
		method: 'DELETE',
		path: 'suppression/invalid_emails',
		body: true,
		inKind: 'deleteSuppressions',
		outKind: 'empty',
	},
	{
		key: 'suppressionsGetGlobalUnsubscribes',
		nested: 'suppressions.getGlobalUnsubscribes',
		risk: 'read',
		description: 'Retrieve global unsubscribes',
		method: 'GET',
		path: 'suppression/unsubscribes',
		queryKeys: ['start_time', 'end_time', 'limit', 'offset'],
		wrapArray: 'results',
		inKind: 'suppressionList',
		outKind: 'results',
	},
	{
		key: 'suppressionsAddGlobalUnsubscribes',
		nested: 'suppressions.addGlobalUnsubscribes',
		risk: 'write',
		description: 'Add emails to the global unsubscribe list',
		method: 'POST',
		path: 'asm/suppressions/global',
		body: true,
		inKind: 'recipientEmails',
		outKind: 'obj',
	},
	{
		key: 'suppressionsGetGlobalUnsubscribe',
		nested: 'suppressions.getGlobalUnsubscribe',
		risk: 'read',
		description: 'Retrieve a global unsubscribe by email',
		method: 'GET',
		path: 'asm/suppressions/global/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'obj',
	},
	{
		key: 'suppressionsDeleteGlobalUnsubscribe',
		nested: 'suppressions.deleteGlobalUnsubscribe',
		risk: 'write',
		description: 'Delete a global unsubscribe by email',
		method: 'DELETE',
		path: 'asm/suppressions/global/{email}',
		pathKeys: ['email'],
		inKind: 'email',
		outKind: 'empty',
	},
	{
		key: 'asmGetGroups',
		nested: 'asm.getGroups',
		risk: 'read',
		description: 'Retrieve unsubscribe groups',
		method: 'GET',
		path: 'asm/groups',
		queryKeys: ['id'],
		inKind: 'asmIdQuery',
		outKind: 'arr',
	},
	{
		key: 'asmCreateGroup',
		nested: 'asm.createGroup',
		risk: 'write',
		description: 'Create an unsubscribe group',
		method: 'POST',
		path: 'asm/groups',
		body: true,
		inKind: 'asmGroup',
		outKind: 'obj',
	},
	{
		key: 'asmGetGroup',
		nested: 'asm.getGroup',
		risk: 'read',
		description: 'Retrieve an unsubscribe group',
		method: 'GET',
		path: 'asm/groups/{id}',
		pathKeys: ['id'],
		inKind: 'idNum',
		outKind: 'obj',
	},
	{
		key: 'asmUpdateGroup',
		nested: 'asm.updateGroup',
		risk: 'write',
		description: 'Update an unsubscribe group',
		method: 'PATCH',
		path: 'asm/groups/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'asmGroupUpdate',
		outKind: 'obj',
	},
	{
		key: 'asmDeleteGroup',
		nested: 'asm.deleteGroup',
		risk: 'write',
		description: 'Delete an unsubscribe group',
		method: 'DELETE',
		path: 'asm/groups/{id}',
		pathKeys: ['id'],
		inKind: 'idNum',
		outKind: 'empty',
	},
	{
		key: 'asmAddGroupSuppressions',
		nested: 'asm.addGroupSuppressions',
		risk: 'write',
		description: 'Add suppressions to an unsubscribe group',
		method: 'POST',
		path: 'asm/groups/{id}/suppressions',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'asmGroupEmails',
		outKind: 'obj',
	},
	{
		key: 'asmGetGroupSuppressions',
		nested: 'asm.getGroupSuppressions',
		risk: 'read',
		description: 'Retrieve suppressions for an unsubscribe group',
		method: 'GET',
		path: 'asm/groups/{id}/suppressions',
		pathKeys: ['id'],
		inKind: 'idNum',
		outKind: 'arr',
	},
	{
		key: 'asmDeleteGroupSuppression',
		nested: 'asm.deleteGroupSuppression',
		risk: 'write',
		description: 'Delete a suppression from an unsubscribe group',
		method: 'DELETE',
		path: 'asm/groups/{id}/suppressions/{email}',
		pathKeys: ['id', 'email'],
		inKind: 'idNumEmail',
		outKind: 'empty',
	},
	{
		key: 'statsGetGlobal',
		nested: 'stats.getGlobal',
		risk: 'read',
		description: 'Retrieve global email statistics',
		method: 'GET',
		path: 'stats',
		queryKeys: ['start_date', 'end_date', 'aggregated_by', 'limit', 'offset'],
		inKind: 'stats',
		outKind: 'arr',
	},
	{
		key: 'statsGetCategory',
		nested: 'stats.getCategory',
		risk: 'read',
		description: 'Retrieve category statistics',
		method: 'GET',
		path: 'categories/stats',
		queryKeys: [
			'start_date',
			'end_date',
			'aggregated_by',
			'categories',
			'limit',
			'offset',
		],
		inKind: 'statsCategories',
		outKind: 'arr',
	},
	{
		key: 'statsGetMailboxProvider',
		nested: 'stats.getMailboxProvider',
		risk: 'read',
		description: 'Retrieve mailbox provider statistics',
		method: 'GET',
		path: 'mailbox_providers/stats',
		queryKeys: [
			'start_date',
			'end_date',
			'aggregated_by',
			'mailbox_providers',
			'limit',
			'offset',
		],
		inKind: 'stats',
		outKind: 'arr',
	},
	{
		key: 'statsGetGeo',
		nested: 'stats.getGeo',
		risk: 'read',
		description: 'Retrieve geographic statistics',
		method: 'GET',
		path: 'geo/stats',
		queryKeys: [
			'start_date',
			'end_date',
			'aggregated_by',
			'country',
			'limit',
			'offset',
		],
		inKind: 'stats',
		outKind: 'arr',
	},
	{
		key: 'statsGetDevice',
		nested: 'stats.getDevice',
		risk: 'read',
		description: 'Retrieve device statistics',
		method: 'GET',
		path: 'devices/stats',
		queryKeys: ['start_date', 'end_date', 'aggregated_by', 'limit', 'offset'],
		inKind: 'stats',
		outKind: 'arr',
	},
	{
		key: 'statsGetClient',
		nested: 'stats.getClient',
		risk: 'read',
		description: 'Retrieve email client statistics',
		method: 'GET',
		path: 'clients/stats',
		queryKeys: ['start_date', 'end_date', 'aggregated_by'],
		inKind: 'stats',
		outKind: 'arr',
	},
	{
		key: 'userGetProfile',
		nested: 'user.getProfile',
		risk: 'read',
		description: 'Retrieve the user profile',
		method: 'GET',
		path: 'user/profile',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'userGetAccount',
		nested: 'user.getAccount',
		risk: 'read',
		description: 'Retrieve the user account',
		method: 'GET',
		path: 'user/account',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'userGetCredits',
		nested: 'user.getCredits',
		risk: 'read',
		description: 'Retrieve remaining email credits',
		method: 'GET',
		path: 'user/credits',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'userGetUsername',
		nested: 'user.getUsername',
		risk: 'read',
		description: 'Retrieve the account username',
		method: 'GET',
		path: 'user/username',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'userGetEmail',
		nested: 'user.getEmail',
		risk: 'read',
		description: 'Retrieve the account email address',
		method: 'GET',
		path: 'user/email',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'userGetScopes',
		nested: 'user.getScopes',
		risk: 'read',
		description: 'Retrieve API key scopes for the current key',
		method: 'GET',
		path: 'scopes',
		inKind: 'empty',
		outKind: 'obj',
	},
	{
		key: 'apiKeysCreate',
		nested: 'apiKeys.create',
		risk: 'write',
		description: 'Create an API key',
		method: 'POST',
		path: 'api_keys',
		body: true,
		inKind: 'apiKeyCreate',
		outKind: 'obj',
	},
	{
		key: 'apiKeysGetAll',
		nested: 'apiKeys.getAll',
		risk: 'read',
		description: 'Retrieve all API keys',
		method: 'GET',
		path: 'api_keys',
		queryKeys: ['limit'],
		inKind: 'limit',
		outKind: 'obj',
	},
	{
		key: 'apiKeysGet',
		nested: 'apiKeys.get',
		risk: 'read',
		description: 'Retrieve an API key',
		method: 'GET',
		path: 'api_keys/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'obj',
	},
	{
		key: 'apiKeysUpdate',
		nested: 'apiKeys.update',
		risk: 'write',
		description: 'Update an API key name or scopes',
		method: 'PUT',
		path: 'api_keys/{id}',
		pathKeys: ['id'],
		body: 'omit',
		inKind: 'apiKeyUpdate',
		outKind: 'obj',
	},
	{
		key: 'apiKeysRemove',
		nested: 'apiKeys.remove',
		risk: 'write',
		description: 'Delete an API key',
		method: 'DELETE',
		path: 'api_keys/{id}',
		pathKeys: ['id'],
		inKind: 'id',
		outKind: 'empty',
	},
];

export const SENDGRID_OPS_BY_KEY = Object.fromEntries(
	SENDGRID_OPS.map((op) => [op.key, op]),
) as Record<string, OpSpec>;
