export type SapRisk = 'read' | 'write' | 'destructive';

export type SapSpecial =
	| 'customMdf'
	| 'goalPlan'
	| 'nominationDelete'
	| 'applicationInterview'
	| 'currentUser';

export type SapRoute = {
	name: string;
	group: string;
	method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
	path: string;
	description: string;
	riskLevel: SapRisk;
	irreversible?: true;
	special?: SapSpecial;
};

export const sapRoutes = [
	{
		name: 'approveCalibrationSession',
		group: 'approve',
		method: 'POST',
		path: 'odata/v4/CalSession.svc/Approve',
		description:
			'Finalize a calibration session that is In Progress or Approving',
		riskLevel: 'write',
	},
	{
		name: 'getCalibrationSessionById',
		group: 'calibration',
		method: 'GET',
		path: 'odata/v4/CalSession.svc/CalibrationSession({session_id})',
		description: 'Get a specific calibration session by session ID',
		riskLevel: 'read',
	},
	{
		name: 'getCalibrationSessions',
		group: 'calibration',
		method: 'GET',
		path: 'odata/v4/CalSession.svc/CalibrationSession',
		description: 'Query all calibration sessions the current user can access',
		riskLevel: 'read',
	},
	{
		name: 'getCalibrationSubjectById',
		group: 'calibration',
		method: 'GET',
		path: 'odata/v4/CalSession.svc/CalibrationSubject({subject_id})',
		description:
			"Query a subject's competency ratings within a calibration session",
		riskLevel: 'read',
	},
	{
		name: 'getCalibrationSubjectRatings',
		group: 'calibration',
		method: 'GET',
		path: 'odata/v4/CalSession.svc/CalibrationSubject',
		description: "Query a subject's ratings by session ID",
		riskLevel: 'read',
	},
	{
		name: 'updateCalibrationSubjectRatings',
		group: 'calibration',
		method: 'PATCH',
		path: 'odata/v4/CalSession.svc/CalibrationSubject({subject_id})',
		description:
			"Update a subject's competency ratings in a calibration session",
		riskLevel: 'write',
	},
	{
		name: 'getOdataMetadataCalibSessionService',
		group: 'odata',
		method: 'GET',
		path: 'odata/v4/CalSession.svc/$metadata',
		description: 'Get OData metadata for Calibration Session service',
		riskLevel: 'read',
	},
	{
		name: 'getOdataMetadataOnboardingAddl',
		group: 'odata',
		method: 'GET',
		path: 'odata/v2/$metadata',
		description: 'Get OData metadata for Onboarding Additional Services',
		riskLevel: 'read',
	},
	{
		name: 'getOdataMetadataForNominationService',
		group: 'odata',
		method: 'GET',
		path: 'odata/v4/NominationService.svc/$metadata',
		description: 'Get OData metadata for Nomination service',
		riskLevel: 'read',
	},
	{
		name: 'getOdataUserMetadata',
		group: 'odata',
		method: 'GET',
		path: 'odata/v2/User/$metadata',
		description: 'Get OData metadata for the User entity',
		riskLevel: 'read',
	},
	{
		name: 'getOdataMetadataClockInclockOut',
		group: 'odata',
		method: 'GET',
		path: 'odata/v2/ClockInClockOutGroup/$metadata',
		description: 'Get OData metadata for Clock In/Clock Out Integration',
		riskLevel: 'read',
	},
	{
		name: 'createOnboardee',
		group: 'onboardee',
		method: 'POST',
		path: 'odata/v2/User',
		description: 'Create a new onboardee (User) for Onboarding 2.0',
		riskLevel: 'write',
	},
	{
		name: 'getOnb2Process',
		group: 'onb2',
		method: 'GET',
		path: 'odata/v2/ONB2Process',
		description: 'Retrieve Onboarding 2.0 process records',
		riskLevel: 'read',
	},
	{
		name: 'updateInternalUsernameNewHiresAfter',
		group: 'internal',
		method: 'POST',
		path: 'odata/v2/updateUserNamePostHiring',
		description: 'Update internal username of new hires after MPH submit',
		riskLevel: 'write',
	},
	{
		name: 'createAFeedbackRequest',
		group: 'a',
		method: 'POST',
		path: 'odata/v4/ContinuousPerformanceManagement.svc/FeedbackRequest',
		description: 'Create a continuous feedback request',
		riskLevel: 'write',
	},
	{
		name: 'getFeedbackRecordsServiceAvailable',
		group: 'feedback',
		method: 'GET',
		path: 'odata/v4/ContinuousPerformanceManagement.svc/Feedback',
		description: 'Retrieve continuous feedback records (OData V4)',
		riskLevel: 'read',
	},
	{
		name: 'getPendingFeedbackRequestsFeedback',
		group: 'pending',
		method: 'GET',
		path: 'odata/v4/ContinuousPerformanceManagement.svc/FeedbackRequest',
		description: 'Retrieve pending feedback requests',
		riskLevel: 'read',
	},
	{
		name: 'giveFeedbackOrRespondToAFeedbackRequest',
		group: 'give',
		method: 'POST',
		path: 'odata/v4/ContinuousPerformanceManagement.svc/Feedback',
		description: 'Give feedback or respond to a feedback request',
		riskLevel: 'write',
	},
	{
		name: 'refreshMetadataContFeedbackService',
		group: 'metadata',
		method: 'POST',
		path: 'odata/v4/ContinuousPerformanceManagement.svc/RefreshMetadata',
		description: 'Refresh metadata cache for Continuous Feedback',
		riskLevel: 'write',
	},
	{
		name: 'createUpdateSuccessorNomination',
		group: 'successor',
		method: 'POST',
		path: 'odata/v4/NominationService.svc/NominationTarget',
		description: 'Create or update a successor nomination',
		riskLevel: 'write',
	},
	{
		name: 'deleteNominationPositionTalentPool',
		group: 'nomination',
		method: 'DELETE',
		path: 'odata/v4/NominationService.svc/NominationTarget({nominationTargetId})',
		description: 'Delete a nomination for a position or talent pool',
		riskLevel: 'destructive',
		irreversible: true,
		special: 'nominationDelete',
	},
	{
		name: 'getTalentPool',
		group: 'talent',
		method: 'GET',
		path: 'odata/v2/TalentPool',
		description: 'Retrieve talent pool records',
		riskLevel: 'read',
	},
	{
		name: 'getApplicationInterview',
		group: 'application',
		method: 'GET',
		path: 'odata/v2/ApplicationInterview',
		description: 'Retrieve interview information for job applications',
		riskLevel: 'read',
		special: 'applicationInterview',
	},
	{
		name: 'getInterviewOverallAssessment',
		group: 'interview',
		method: 'GET',
		path: 'odata/v2/OverallInterviewAssessment',
		description: 'Retrieve overall interview ratings',
		riskLevel: 'read',
	},
	{
		name: 'getJobApplication',
		group: 'job',
		method: 'GET',
		path: 'odata/v2/JobApplication',
		description: 'Retrieve job application records',
		riskLevel: 'read',
	},
	{
		name: 'getJobRequisition',
		group: 'job',
		method: 'GET',
		path: 'odata/v2/JobRequisition',
		description: 'Retrieve job requisition records',
		riskLevel: 'read',
	},
	{
		name: 'getJobReqScreeningQuestion',
		group: 'job',
		method: 'GET',
		path: 'odata/v2/JobReqScreeningQuestion',
		description: 'Retrieve screening questions for job requisitions',
		riskLevel: 'read',
	},
	{
		name: 'listCandidates',
		group: 'candidates',
		method: 'GET',
		path: 'odata/v2/Candidate',
		description: 'Retrieve candidates',
		riskLevel: 'read',
	},
	{
		name: 'getFoBusinessUnit',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOBusinessUnit',
		description: 'Retrieve FOBusinessUnit records',
		riskLevel: 'read',
	},
	{
		name: 'getFoCompany',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOCompany',
		description: 'Retrieve FOCompany records',
		riskLevel: 'read',
	},
	{
		name: 'getFoCostCenter',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOCostCenter',
		description: 'Retrieve FOCostCenter records',
		riskLevel: 'read',
	},
	{
		name: 'getFoDepartment',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FODepartment',
		description: 'Retrieve FODepartment records',
		riskLevel: 'read',
	},
	{
		name: 'getFoJobCode',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOJobCode',
		description: 'Retrieve FOJobCode records',
		riskLevel: 'read',
	},
	{
		name: 'getFoJobFunction',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOJobFunction',
		description: 'Retrieve FOJobFunction records',
		riskLevel: 'read',
	},
	{
		name: 'getFoLocation',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOLocation',
		description: 'Retrieve FOLocation records',
		riskLevel: 'read',
	},
	{
		name: 'getFoPayGroup',
		group: 'fo',
		method: 'GET',
		path: 'odata/v2/FOPayGroup',
		description: 'Retrieve FOPayGroup records',
		riskLevel: 'read',
	},
	{
		name: 'getPosition',
		group: 'position',
		method: 'GET',
		path: 'odata/v2/Position',
		description: 'Retrieve position management records',
		riskLevel: 'read',
	},
	{
		name: 'getCustomMdfObject',
		group: 'custom',
		method: 'GET',
		path: 'odata/v2/{custom_object}',
		description: 'Retrieve custom MDF objects (cust_* entities)',
		riskLevel: 'read',
		special: 'customMdf',
	},
	{
		name: 'getPicklist',
		group: 'picklist',
		method: 'GET',
		path: 'odata/v2/Picklist',
		description: 'Retrieve picklist definitions',
		riskLevel: 'read',
	},
	{
		name: 'getPicklistOption',
		group: 'picklist',
		method: 'GET',
		path: 'odata/v2/PicklistOption',
		description: 'Retrieve picklist option values',
		riskLevel: 'read',
	},
	{
		name: 'getCurrentUser',
		group: 'current',
		method: 'GET',
		path: 'odata/v2/User',
		description: 'Retrieve the currently authenticated user',
		riskLevel: 'read',
		special: 'currentUser',
	},
	{
		name: 'listUsers',
		group: 'users',
		method: 'GET',
		path: 'odata/v2/User',
		description: 'List User entity records',
		riskLevel: 'read',
	},
	{
		name: 'getPerPersonById',
		group: 'per',
		method: 'GET',
		path: 'odata/v2/PerPerson({person_id_external})',
		description: 'Retrieve PerPerson by personIdExternal',
		riskLevel: 'read',
	},
	{
		name: 'listPerPerson',
		group: 'per',
		method: 'GET',
		path: 'odata/v2/PerPerson',
		description: 'List PerPerson records',
		riskLevel: 'read',
	},
	{
		name: 'getPerPersonal',
		group: 'per',
		method: 'GET',
		path: 'odata/v2/PerPersonal',
		description: 'Retrieve PerPersonal biographical records',
		riskLevel: 'read',
	},
	{
		name: 'getBackgroundEducation',
		group: 'background',
		method: 'GET',
		path: 'odata/v2/Background_Education',
		description: 'Retrieve Background_Education records',
		riskLevel: 'read',
	},
	{
		name: 'getBackgroundMobility',
		group: 'background',
		method: 'GET',
		path: 'odata/v2/Background_Mobility',
		description: 'Retrieve Background_Mobility records',
		riskLevel: 'read',
	},
	{
		name: 'listEmpEmployment',
		group: 'emp',
		method: 'GET',
		path: 'odata/v2/EmpEmployment',
		description: 'List EmpEmployment records',
		riskLevel: 'read',
	},
	{
		name: 'getEmpEmploymentTermination',
		group: 'emp',
		method: 'GET',
		path: 'odata/v2/EmpEmploymentTermination',
		description: 'Retrieve EmpEmploymentTermination records',
		riskLevel: 'read',
	},
	{
		name: 'getEmpPayCompRecurring',
		group: 'emp',
		method: 'GET',
		path: 'odata/v2/EmpPayCompRecurring',
		description: 'Retrieve EmpPayCompRecurring records',
		riskLevel: 'read',
	},
	{
		name: 'getEmpPayCompNonRecurring',
		group: 'emp',
		method: 'GET',
		path: 'odata/v2/EmpPayCompNonRecurring',
		description: 'Retrieve EmpPayCompNonRecurring records',
		riskLevel: 'read',
	},
	{
		name: 'getWorkOrder',
		group: 'work',
		method: 'GET',
		path: 'odata/v2/WorkOrder',
		description: 'Retrieve WorkOrder records for contingent workers',
		riskLevel: 'read',
	},
	{
		name: 'getGoalPlanTemplate',
		group: 'goal',
		method: 'GET',
		path: 'odata/v2/GoalPlanTemplate',
		description: 'Retrieve goal plan template records',
		riskLevel: 'read',
	},
	{
		name: 'getGoalsByPlan',
		group: 'goals',
		method: 'GET',
		path: 'odata/v2/Goal_{goal_plan_id}',
		description: 'Retrieve goals for a Goal_<planId> entity',
		riskLevel: 'read',
		special: 'goalPlan',
	},
	{
		name: 'getFormContent',
		group: 'form',
		method: 'GET',
		path: 'odata/v2/FormContent',
		description: 'Retrieve performance form content',
		riskLevel: 'read',
	},
	{
		name: 'createLearningActivitiesBulk',
		group: 'learning',
		method: 'POST',
		path: 'odata/v2/LearningActivity',
		description: 'Create learning activities in bulk',
		riskLevel: 'write',
	},
	{
		name: 'getCdpLearningMetadata',
		group: 'cdp',
		method: 'GET',
		path: 'odata/v2/$metadata',
		description: 'Get metadata for Career Development Planning Learning',
		riskLevel: 'read',
	},
	{
		name: 'refreshCdpLearningMetadata',
		group: 'cdp',
		method: 'POST',
		path: 'odata/v2/refreshCDPLearningMetadata',
		description: 'Refresh CDP Learning metadata',
		riskLevel: 'write',
	},
	{
		name: 'getEmployeeTime',
		group: 'employee',
		method: 'GET',
		path: 'odata/v2/EmployeeTime',
		description: 'Retrieve EmployeeTime records',
		riskLevel: 'read',
	},
	{
		name: 'getEmployeeTimesheet',
		group: 'employee',
		method: 'GET',
		path: 'odata/v2/EmployeeTimeSheet',
		description: 'Retrieve EmployeeTimeSheet records',
		riskLevel: 'read',
	},
	{
		name: 'getTemporaryTimeInformation',
		group: 'temporary',
		method: 'GET',
		path: 'odata/v2/TemporaryTimeInformation',
		description: 'Retrieve TemporaryTimeInformation records',
		riskLevel: 'read',
	},
	{
		name: 'getTimeAccountSnapshot',
		group: 'time',
		method: 'GET',
		path: 'odata/v2/TimeAccountSnapshot',
		description: 'Retrieve TimeAccountSnapshot records',
		riskLevel: 'read',
	},
	{
		name: 'queryAllAvailableClockClockOut',
		group: 'query',
		method: 'GET',
		path: 'odata/v2/ClockInClockOutGroup',
		description: 'Query all clock in/out groups',
		riskLevel: 'read',
	},
	{
		name: 'queryClockClockOutGroupCodeTime',
		group: 'query',
		method: 'GET',
		path: 'odata/v2/ClockInClockOutGroup({code})',
		description: 'Query a clock in/out group by code',
		riskLevel: 'read',
	},
] as const satisfies readonly SapRoute[];

export type SapRouteName = (typeof sapRoutes)[number]['name'];

export const sapRouteByName = Object.fromEntries(
	sapRoutes.map((route) => [route.name, route]),
) as { [K in SapRouteName]: Extract<(typeof sapRoutes)[number], { name: K }> };

export function getSapRoute(name: SapRouteName): SapRoute {
	return sapRouteByName[name];
}
